export interface Product {
  id: string;
  sku: string;
  title: string;
  brand: string;
  category: string;
  gender: 'Women' | 'Men' | 'Unisex';
  price: number;
  originalPrice?: number;
  rating: number;
  reviewCount: number;
  image: string;
  description: string;
  tags: string[];
  sizes: string[];
  colors: string[];
  stockQuantity: number;
  inStock: boolean;
  badge?: 'New Arrival' | 'Bestseller' | 'Sale' | 'Limited';
}

export const CATEGORIES = [
// Women's'Dresses','Tops','Shirts','T-Shirts','Jeans','Pants','Shorts','Skirts','Blazers','Jackets','Hoodies','Knitwear','Coats','Shoes','Sandals','Heels','Boots','Bags','Jewellery','Sunglasses',
// Men's
'Polo Shirts',
'Chinos',
'Sweatshirts',
'Sneakers',
'Watches',
'Accessories'] as
const;

export const BRANDS = ['AUREN'] as const;

export const PRODUCTS: Product[] = [
// ─── WOMEN'S DRESSES ───────────────────────────────────────────────────────
{
  id: 'w-dr-001', sku: 'AUR-W-DR-001', title: 'Velour Wrap Midi Dress', brand: 'AUREN', category: 'Dresses', gender: 'Women', price: 285, rating: 4.8, reviewCount: 312, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1c13c416a-1767328860544.png", description: 'Fluid wrap silhouette in a luxurious velour fabric. Adjustable tie waist, V-neckline, midi length. Fully lined.',
  tags: ['wrap', 'midi', 'velour', 'evening'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Midnight Black', 'Deep Burgundy', 'Forest Green'],
  stockQuantity: 48,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'w-dr-002', sku: 'AUR-W-DR-002', title: 'Linen Shirt Dress — Ivory', brand: 'AUREN', category: 'Dresses', gender: 'Women', price: 195, rating: 4.6, reviewCount: 187, image: "https://img.rocket.new/generatedImages/rocket_gen_img_19ceaba08-1772398498684.png", description: 'Relaxed shirt dress in premium washed linen. Button-front placket, chest pockets, belted waist.',
  tags: ['linen', 'shirt dress', 'casual', 'summer'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['Ivory', 'Sand', 'Sage'],
  stockQuantity: 62,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'w-dr-003', sku: 'AUR-W-DR-003', title: 'Silk Charmeuse Slip Dress', brand: 'AUREN', category: 'Dresses', gender: 'Women', price: 345, originalPrice: 420, rating: 4.9, reviewCount: 428, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1bd41b549-1772898227568.png", description: '100% silk charmeuse slip dress with adjustable spaghetti straps and a bias-cut hem. Effortlessly elegant.',
  tags: ['silk', 'slip dress', 'luxury', 'evening'],
  sizes: ['XS', 'S', 'M', 'L'],
  colors: ['Champagne', 'Onyx', 'Blush Rose'],
  stockQuantity: 30,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'w-dr-004', sku: 'AUR-W-DR-004', title: 'Structured Ponte Sheath Dress', brand: 'AUREN', category: 'Dresses', gender: 'Women', price: 225, rating: 4.5, reviewCount: 203, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1adacd0cc-1782962549609.png", description: 'Tailored sheath dress in stretch ponte fabric. Knee-length, back vent, invisible zip.',
  tags: ['sheath', 'ponte', 'workwear', 'tailored'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Charcoal', 'Navy', 'Cream'],
  stockQuantity: 55,
  inStock: true
},
{
  id: 'w-dr-005', sku: 'AUR-W-DR-005', title: 'Floral Chiffon Maxi Dress', brand: 'AUREN', category: 'Dresses', gender: 'Women', price: 265, rating: 4.7, reviewCount: 341, image: "https://img.rocket.new/generatedImages/rocket_gen_img_166343403-1772898229543.png", description: 'Flowing chiffon maxi dress with an abstract floral print. Smocked bodice, flutter sleeves.',
  tags: ['floral', 'chiffon', 'maxi', 'summer'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Ivory Floral', 'Sage Floral'],
  stockQuantity: 40,
  inStock: true,
  badge: 'New Arrival'
},
// ─── WOMEN'S TOPS ──────────────────────────────────────────────────────────
{
  id: 'w-tp-001',
  sku: 'AUR-W-TP-001',
  title: 'Satin Cami Top — Champagne',
  brand: 'AUREN',
  category: 'Tops',
  gender: 'Women',
  price: 95,
  rating: 4.6,
  reviewCount: 289,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_14f4c2c86-1772097372687.png",
  description: 'Lightweight satin cami with adjustable straps and a lace-trimmed hem. Versatile day-to-night styling.',
  tags: ['cami', 'satin', 'evening', 'layering'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Champagne', 'Black', 'Dusty Rose'],
  stockQuantity: 75,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'w-tp-002',
  sku: 'AUR-W-TP-002',
  title: 'Ribbed Knit Crop Top',
  brand: 'AUREN',
  category: 'Tops',
  gender: 'Women',
  price: 75,
  rating: 4.5,
  reviewCount: 412,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1dabd61bc-1778803688112.png",
  description: 'Slim-fit ribbed knit crop top with a scoop neckline. Soft cotton-modal blend.',
  tags: ['ribbed', 'crop', 'casual', 'knit'],
  sizes: ['XS', 'S', 'M', 'L'],
  colors: ['Oat', 'Black', 'Terracotta', 'Sage'],
  stockQuantity: 90,
  inStock: true
},
{
  id: 'w-tp-003',
  sku: 'AUR-W-TP-003',
  title: 'Linen Bandeau Top',
  brand: 'AUREN',
  category: 'Tops',
  gender: 'Women',
  price: 65,
  rating: 4.4,
  reviewCount: 156,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_12f9134a0-1772153812436.png",
  description: 'Structured linen bandeau with boning detail. Strapless silhouette, back zip closure.',
  tags: ['bandeau', 'linen', 'summer', 'strapless'],
  sizes: ['XS', 'S', 'M', 'L'],
  colors: ['White', 'Sand', 'Cobalt'],
  stockQuantity: 45,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'w-tp-004',
  sku: 'AUR-W-TP-004',
  title: 'Draped Crepe Blouse',
  brand: 'AUREN',
  category: 'Tops',
  gender: 'Women',
  price: 135,
  rating: 4.7,
  reviewCount: 198,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_19724ab0b-1772200145038.png",
  description: 'Elegant draped blouse in matte crepe. Asymmetric hem, flutter sleeves, relaxed fit.',
  tags: ['crepe', 'draped', 'blouse', 'workwear'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Ivory', 'Slate Blue', 'Blush'],
  stockQuantity: 60,
  inStock: true
},
// ─── WOMEN'S SHIRTS ────────────────────────────────────────────────────────
{
  id: 'w-sh-001', sku: 'AUR-W-SH-001', title: 'Oversized Cotton Poplin Shirt', brand: 'AUREN', category: 'Shirts', gender: 'Women', price: 115, rating: 4.7, reviewCount: 523, image: "https://img.rocket.new/generatedImages/rocket_gen_img_14eac7032-1767805645912.png", description: 'Relaxed oversized shirt in crisp cotton poplin. Classic collar, chest pocket, curved hem.',
  tags: ['poplin', 'oversized', 'classic', 'casual'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['White', 'Light Blue', 'Pale Pink', 'Sage'],
  stockQuantity: 110,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'w-sh-002', sku: 'AUR-W-SH-002', title: 'Silk Blend Utility Shirt', brand: 'AUREN', category: 'Shirts', gender: 'Women', price: 185, originalPrice: 230, rating: 4.6, reviewCount: 214, image: "https://img.rocket.new/generatedImages/rocket_gen_img_19ceaba08-1772398498684.png", description: 'Luxurious silk-blend utility shirt with patch pockets and a relaxed silhouette.',
  tags: ['silk', 'utility', 'shirt', 'premium'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Ecru', 'Midnight', 'Caramel'],
  stockQuantity: 38,
  inStock: true,
  badge: 'Sale'
},
// ─── WOMEN'S T-SHIRTS ──────────────────────────────────────────────────────
{
  id: 'w-ts-001',
  sku: 'AUR-W-TS-001',
  title: 'Pima Cotton Crew Tee',
  brand: 'AUREN',
  category: 'T-Shirts',
  gender: 'Women',
  price: 55,
  rating: 4.8,
  reviewCount: 876,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1778e7d8a-1777123978505.png",
  description: '100% Peruvian Pima cotton. Relaxed fit, crew neck, pre-washed for softness.',
  tags: ['pima', 'cotton', 'basic', 'essential'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['White', 'Black', 'Grey Marl', 'Navy', 'Dusty Pink'],
  stockQuantity: 200,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'w-ts-002',
  sku: 'AUR-W-TS-002',
  title: 'Vintage Wash Graphic Tee',
  brand: 'AUREN',
  category: 'T-Shirts',
  gender: 'Women',
  price: 65,
  rating: 4.5,
  reviewCount: 342,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_131cb84ef-1779113904666.png",
  description: 'Vintage-washed cotton tee with a subtle AUREN graphic. Boxy fit, dropped shoulders.',
  tags: ['graphic', 'vintage', 'boxy', 'casual'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Washed Black', 'Washed White', 'Washed Indigo'],
  stockQuantity: 85,
  inStock: true,
  badge: 'New Arrival'
},
// ─── WOMEN'S JEANS ─────────────────────────────────────────────────────────
{
  id: 'w-jn-001', sku: 'AUR-W-JN-001', title: 'High-Rise Straight Leg Jeans', brand: 'AUREN', category: 'Jeans', gender: 'Women', price: 175, rating: 4.7, reviewCount: 634, image: "https://img.rocket.new/generatedImages/rocket_gen_img_187ee4b96-1764925789540.png", description: 'Classic high-rise straight leg in premium Japanese selvedge denim. Five-pocket styling.',
  tags: ['straight leg', 'high-rise', 'selvedge', 'denim'],
  sizes: ['24', '25', '26', '27', '28', '29', '30', '31', '32'],
  colors: ['Indigo', 'Light Wash', 'Black'],
  stockQuantity: 95,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'w-jn-002', sku: 'AUR-W-JN-002', title: 'Wide Leg Barrel Jeans', brand: 'AUREN', category: 'Jeans', gender: 'Women', price: 195, rating: 4.6, reviewCount: 287, image: "https://img.rocket.new/generatedImages/rocket_gen_img_132cbbe50-1764852934828.png", description: 'Relaxed barrel-leg silhouette in soft stretch denim. High waist, cropped length.',
  tags: ['wide leg', 'barrel', 'relaxed', 'denim'],
  sizes: ['24', '25', '26', '27', '28', '29', '30'],
  colors: ['Mid Wash', 'Ecru', 'Dark Indigo'],
  stockQuantity: 70,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'w-jn-003', sku: 'AUR-W-JN-003', title: 'Skinny Ankle Jeans — Dark Wash', brand: 'AUREN', category: 'Jeans', gender: 'Women', price: 155, originalPrice: 195, rating: 4.5, reviewCount: 512, image: "https://img.rocket.new/generatedImages/rocket_gen_img_132cbbe50-1764852934828.png", description: 'Slim-fit ankle jeans in a dark indigo wash. Stretch denim for all-day comfort.',
  tags: ['skinny', 'ankle', 'dark wash', 'slim'],
  sizes: ['24', '25', '26', '27', '28', '29', '30', '31'],
  colors: ['Dark Indigo', 'Black'],
  stockQuantity: 80,
  inStock: true,
  badge: 'Sale'
},
// ─── WOMEN'S PANTS ─────────────────────────────────────────────────────────
{
  id: 'w-pt-001',
  sku: 'AUR-W-PT-001',
  title: 'Tailored Wide-Leg Trousers',
  brand: 'AUREN',
  category: 'Pants',
  gender: 'Women',
  price: 215,
  rating: 4.8,
  reviewCount: 398,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_17b051cc6-1772354892991.png",
  description: 'High-waisted wide-leg trousers in a premium wool-blend fabric. Pressed crease, side pockets.',
  tags: ['wide-leg', 'tailored', 'wool', 'workwear'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Charcoal', 'Camel', 'Ivory', 'Black'],
  stockQuantity: 65,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'w-pt-002',
  sku: 'AUR-W-PT-002',
  title: 'Satin Jogger Pants',
  brand: 'AUREN',
  category: 'Pants',
  gender: 'Women',
  price: 145,
  rating: 4.5,
  reviewCount: 231,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_104bfdaac-1779840015734.png",
  description: 'Luxe satin jogger with elasticated waist and cuffed ankles. Relaxed, effortless silhouette.',
  tags: ['satin', 'jogger', 'relaxed', 'lounge'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Champagne', 'Black', 'Dusty Mauve'],
  stockQuantity: 50,
  inStock: true,
  badge: 'New Arrival'
},
// ─── WOMEN'S SHORTS ────────────────────────────────────────────────────────
{
  id: 'w-so-001', sku: 'AUR-W-SO-001', title: 'Linen Tailored Shorts', brand: 'AUREN', category: 'Shorts', gender: 'Women', price: 95, rating: 4.6, reviewCount: 178, image: "https://img.rocket.new/generatedImages/rocket_gen_img_13ee713a4-1772990706884.png", description: 'Mid-rise tailored shorts in washed linen. Pleat front, side pockets, zip fly.',
  tags: ['linen', 'tailored', 'shorts', 'summer'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Sand', 'White', 'Sage', 'Navy'],
  stockQuantity: 72,
  inStock: true
},
{
  id: 'w-so-002', sku: 'AUR-W-SO-002', title: 'Denim Cut-Off Shorts', brand: 'AUREN', category: 'Shorts', gender: 'Women', price: 85, rating: 4.4, reviewCount: 265, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1559cedb8-1772285180467.png", description: 'High-waisted denim shorts with a raw hem and subtle distressing. Classic five-pocket styling.',
  tags: ['denim', 'cut-off', 'casual', 'summer'],
  sizes: ['24', '25', '26', '27', '28', '29', '30'],
  colors: ['Light Wash', 'Mid Wash', 'Black'],
  stockQuantity: 88,
  inStock: true,
  badge: 'New Arrival'
},
// ─── WOMEN'S SKIRTS ────────────────────────────────────────────────────────
{
  id: 'w-sk-001',
  sku: 'AUR-W-SK-001',
  title: 'Pleated Midi Skirt — Ivory',
  brand: 'AUREN',
  category: 'Skirts',
  gender: 'Women',
  price: 145,
  rating: 4.7,
  reviewCount: 312,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_14a2b5c5e-1768239327982.png",
  description: 'Flowing pleated midi skirt in a lightweight crepe fabric. Elasticated waist, fully lined.',
  tags: ['pleated', 'midi', 'crepe', 'elegant'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Ivory', 'Blush', 'Sage', 'Black'],
  stockQuantity: 60,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'w-sk-002',
  sku: 'AUR-W-SK-002',
  title: 'Leather Mini Skirt',
  brand: 'AUREN',
  category: 'Skirts',
  gender: 'Women',
  price: 195,
  rating: 4.6,
  reviewCount: 198,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_16a844ee7-1772329170417.png",
  description: 'Sleek mini skirt in premium vegan leather. A-line silhouette, back zip, fully lined.',
  tags: ['leather', 'mini', 'edgy', 'evening'],
  sizes: ['XS', 'S', 'M', 'L'],
  colors: ['Black', 'Chocolate', 'Camel'],
  stockQuantity: 42,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'w-sk-003',
  sku: 'AUR-W-SK-003',
  title: 'Denim Maxi Skirt',
  brand: 'AUREN',
  category: 'Skirts',
  gender: 'Women',
  price: 165,
  originalPrice: 210,
  rating: 4.5,
  reviewCount: 143,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1c60fabde-1764820616651.png",
  description: 'Floor-length denim maxi skirt with a front slit. High waist, zip fly, five-pocket styling.',
  tags: ['denim', 'maxi', 'casual', 'boho'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Indigo', 'Light Wash'],
  stockQuantity: 55,
  inStock: true,
  badge: 'Sale'
},
// ─── WOMEN'S BLAZERS ───────────────────────────────────────────────────────
{
  id: 'w-bl-001', sku: 'AUR-W-BL-001', title: 'Double-Breasted Power Blazer', brand: 'AUREN', category: 'Blazers', gender: 'Women', price: 345, rating: 4.8, reviewCount: 267, image: "https://img.rocket.new/generatedImages/rocket_gen_img_16a1b93b5-1772278897887.png", description: 'Structured double-breasted blazer in a premium wool-blend. Peak lapels, padded shoulders, fully lined.',
  tags: ['double-breasted', 'power blazer', 'tailored', 'workwear'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Charcoal', 'Camel', 'Ivory', 'Black'],
  stockQuantity: 40,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'w-bl-002', sku: 'AUR-W-BL-002', title: 'Linen Relaxed Blazer', brand: 'AUREN', category: 'Blazers', gender: 'Women', price: 225, rating: 4.6, reviewCount: 189, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1567905b1-1767587100933.png", description: 'Relaxed-fit linen blazer with a notch lapel. Welt pockets, unlined for a lightweight feel.',
  tags: ['linen', 'relaxed', 'blazer', 'summer'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['Oat', 'Navy', 'Sage', 'Black'],
  stockQuantity: 58,
  inStock: true,
  badge: 'New Arrival'
},
// ─── WOMEN'S JACKETS ───────────────────────────────────────────────────────
{
  id: 'w-jk-001',
  sku: 'AUR-W-JK-001',
  title: 'Quilted Puffer Jacket',
  brand: 'AUREN',
  category: 'Jackets',
  gender: 'Women',
  price: 295,
  rating: 4.7,
  reviewCount: 412,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1345dfd14-1774047263705.png",
  description: 'Lightweight quilted puffer with recycled down fill. Stand collar, zip pockets, packable.',
  tags: ['puffer', 'quilted', 'down', 'winter'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Black', 'Camel', 'Forest Green', 'Dusty Rose'],
  stockQuantity: 65,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'w-jk-002',
  sku: 'AUR-W-JK-002',
  title: 'Leather Moto Jacket',
  brand: 'AUREN',
  category: 'Jackets',
  gender: 'Women',
  price: 485,
  rating: 4.9,
  reviewCount: 198,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1dbfdf5e1-1773092398832.png",
  description: 'Premium lambskin leather moto jacket. Asymmetric zip, quilted shoulders, silver hardware.',
  tags: ['leather', 'moto', 'biker', 'premium'],
  sizes: ['XS', 'S', 'M', 'L'],
  colors: ['Black', 'Cognac'],
  stockQuantity: 25,
  inStock: true,
  badge: 'New Arrival'
},
// ─── WOMEN'S HOODIES ───────────────────────────────────────────────────────
{
  id: 'w-hd-001', sku: 'AUR-W-HD-001', title: 'Cashmere Blend Hoodie', brand: 'AUREN', category: 'Hoodies', gender: 'Women', price: 195, rating: 4.8, reviewCount: 534, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1af5436a4-1772227652113.png", description: 'Luxuriously soft cashmere-blend hoodie. Relaxed fit, kangaroo pocket, ribbed cuffs and hem.',
  tags: ['cashmere', 'hoodie', 'luxury', 'lounge'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Oat', 'Charcoal', 'Blush', 'Sage'],
  stockQuantity: 80,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'w-hd-002', sku: 'AUR-W-HD-002', title: 'Oversized French Terry Hoodie', brand: 'AUREN', category: 'Hoodies', gender: 'Women', price: 125, rating: 4.6, reviewCount: 389, image: "https://img.rocket.new/generatedImages/rocket_gen_img_107911ff1-1778765520697.png", description: 'Oversized hoodie in heavyweight French terry cotton. Dropped shoulders, kangaroo pocket.',
  tags: ['french terry', 'oversized', 'casual', 'cotton'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['White', 'Black', 'Grey Marl', 'Dusty Pink'],
  stockQuantity: 100,
  inStock: true
},
// ─── WOMEN'S KNITWEAR ──────────────────────────────────────────────────────
{
  id: 'w-kn-001',
  sku: 'AUR-W-KN-001',
  title: 'Merino Wool Turtleneck Sweater',
  brand: 'AUREN',
  category: 'Knitwear',
  gender: 'Women',
  price: 185,
  rating: 4.8,
  reviewCount: 621,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_13c7fea5e-1773122125487.png",
  description: 'Fine-gauge merino wool turtleneck. Slim fit, ribbed cuffs and hem. Machine washable.',
  tags: ['merino', 'turtleneck', 'wool', 'winter'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Ivory', 'Camel', 'Black', 'Dusty Rose', 'Forest Green'],
  stockQuantity: 75,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'w-kn-002',
  sku: 'AUR-W-KN-002',
  title: 'Chunky Cable Knit Cardigan',
  brand: 'AUREN',
  category: 'Knitwear',
  gender: 'Women',
  price: 215,
  rating: 4.7,
  reviewCount: 287,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1f719b717-1767006403012.png",
  description: 'Oversized cable-knit cardigan in a premium wool blend. Shawl collar, patch pockets, button front.',
  tags: ['cable knit', 'cardigan', 'oversized', 'cosy'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Oat', 'Caramel', 'Charcoal'],
  stockQuantity: 55,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'w-kn-003',
  sku: 'AUR-W-KN-003',
  title: 'Cashmere V-Neck Pullover',
  brand: 'AUREN',
  category: 'Knitwear',
  gender: 'Women',
  price: 265,
  originalPrice: 320,
  rating: 4.9,
  reviewCount: 445,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_101a8f6e4-1767171055972.png",
  description: 'Grade-A cashmere V-neck pullover. Relaxed fit, ribbed trim. Available in 8 colours.',
  tags: ['cashmere', 'v-neck', 'luxury', 'pullover'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Ivory', 'Camel', 'Navy', 'Black', 'Blush', 'Sage', 'Burgundy', 'Grey'],
  stockQuantity: 60,
  inStock: true,
  badge: 'Sale'
},
// ─── WOMEN'S COATS ─────────────────────────────────────────────────────────
{
  id: 'w-ct-001', sku: 'AUR-W-CT-001', title: 'Camel Wool Wrap Coat', brand: 'AUREN', category: 'Coats', gender: 'Women', price: 595, rating: 4.9, reviewCount: 312, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1949a758a-1772375674274.png", description: 'Classic wrap coat in a premium Italian wool blend. Notch lapel, self-tie belt, fully lined.',
  tags: ['wrap coat', 'wool', 'camel', 'classic'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Camel', 'Black', 'Ivory'],
  stockQuantity: 35,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'w-ct-002', sku: 'AUR-W-CT-002', title: 'Oversized Teddy Coat', brand: 'AUREN', category: 'Coats', gender: 'Women', price: 445, rating: 4.7, reviewCount: 198, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1d02a897a-1774919423631.png", description: 'Cosy oversized teddy coat in a plush faux shearling. Lapel collar, patch pockets.',
  tags: ['teddy', 'shearling', 'oversized', 'winter'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Oat', 'Chocolate', 'Black'],
  stockQuantity: 42,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'w-ct-003', sku: 'AUR-W-CT-003', title: 'Longline Trench Coat', brand: 'AUREN', category: 'Coats', gender: 'Women', price: 485, originalPrice: 595, rating: 4.8, reviewCount: 267, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1ddddab20-1781353332583.png", description: 'Classic double-breasted trench coat in water-resistant cotton gabardine. Storm flap, epaulettes.',
  tags: ['trench', 'classic', 'water-resistant', 'timeless'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Camel', 'Black', 'Navy'],
  stockQuantity: 30,
  inStock: true,
  badge: 'Sale'
},
// ─── WOMEN'S SHOES ─────────────────────────────────────────────────────────
{
  id: 'w-sw-001',
  sku: 'AUR-W-SW-001',
  title: 'Leather Ballet Flat',
  brand: 'AUREN',
  category: 'Shoes',
  gender: 'Women',
  price: 195,
  rating: 4.7,
  reviewCount: 523,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1e59dc9c2-1772902430280.png",
  description: 'Classic ballet flat in supple nappa leather. Elasticated topline, leather sole.',
  tags: ['ballet flat', 'leather', 'classic', 'everyday'],
  sizes: ['35', '36', '37', '38', '39', '40', '41'],
  colors: ['Black', 'Nude', 'White', 'Burgundy'],
  stockQuantity: 80,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'w-sw-002',
  sku: 'AUR-W-SW-002',
  title: 'Suede Loafer',
  brand: 'AUREN',
  category: 'Shoes',
  gender: 'Women',
  price: 225,
  rating: 4.6,
  reviewCount: 312,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1d53f120b-1772157997916.png",
  description: 'Chunky-soled loafer in premium suede. Penny strap detail, lug sole.',
  tags: ['loafer', 'suede', 'chunky', 'casual'],
  sizes: ['35', '36', '37', '38', '39', '40', '41'],
  colors: ['Camel', 'Black', 'Chocolate'],
  stockQuantity: 65,
  inStock: true,
  badge: 'New Arrival'
},
// ─── WOMEN'S SANDALS ───────────────────────────────────────────────────────
{
  id: 'w-sa-001', sku: 'AUR-W-SA-001', title: 'Leather Strappy Sandal', brand: 'AUREN', category: 'Sandals', gender: 'Women', price: 175, rating: 4.6, reviewCount: 289, image: "https://img.rocket.new/generatedImages/rocket_gen_img_10bac3c4d-1772218103829.png", description: 'Minimalist strappy sandal in vegetable-tanned leather. Adjustable ankle strap, flat sole.',
  tags: ['strappy', 'leather', 'flat', 'summer'],
  sizes: ['35', '36', '37', '38', '39', '40', '41'],
  colors: ['Tan', 'Black', 'White'],
  stockQuantity: 70,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'w-sa-002', sku: 'AUR-W-SA-002', title: 'Espadrille Wedge Sandal', brand: 'AUREN', category: 'Sandals', gender: 'Women', price: 145, rating: 4.5, reviewCount: 198, image: "https://img.rocket.new/generatedImages/rocket_gen_img_114281eb2-1767444096926.png", description: 'Espadrille wedge sandal with a jute-wrapped platform. Ankle tie, canvas upper.',
  tags: ['espadrille', 'wedge', 'summer', 'casual'],
  sizes: ['35', '36', '37', '38', '39', '40'],
  colors: ['Natural', 'Black', 'Navy'],
  stockQuantity: 55,
  inStock: true
},
// ─── WOMEN'S HEELS ─────────────────────────────────────────────────────────
{
  id: 'w-hl-001',
  sku: 'AUR-W-HL-001',
  title: 'Pointed-Toe Stiletto Heel',
  brand: 'AUREN',
  category: 'Heels',
  gender: 'Women',
  price: 285,
  rating: 4.7,
  reviewCount: 312,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_176810785-1772899226740.png",
  description: 'Classic pointed-toe stiletto in patent leather. 90mm heel, leather sole.',
  tags: ['stiletto', 'pointed-toe', 'patent', 'evening'],
  sizes: ['35', '36', '37', '38', '39', '40', '41'],
  colors: ['Black', 'Nude', 'Red'],
  stockQuantity: 45,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'w-hl-002',
  sku: 'AUR-W-HL-002',
  title: 'Block Heel Mule',
  brand: 'AUREN',
  category: 'Heels',
  gender: 'Women',
  price: 215,
  rating: 4.6,
  reviewCount: 245,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1ffd915c4-1772348738892.png",
  description: 'Open-toe mule with a stable block heel. Suede upper, 70mm heel height.',
  tags: ['mule', 'block heel', 'suede', 'everyday'],
  sizes: ['35', '36', '37', '38', '39', '40', '41'],
  colors: ['Camel', 'Black', 'Blush'],
  stockQuantity: 60,
  inStock: true,
  badge: 'New Arrival'
},
// ─── WOMEN'S BOOTS ─────────────────────────────────────────────────────────
{
  id: 'w-bt-001', sku: 'AUR-W-BT-001', title: 'Knee-High Leather Boot', brand: 'AUREN', category: 'Boots', gender: 'Women', price: 495, rating: 4.8, reviewCount: 387, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1b77b1252-1777038506724.png", description: 'Knee-high boot in smooth calf leather. Block heel, inside zip, leather sole.',
  tags: ['knee-high', 'leather', 'classic', 'autumn'],
  sizes: ['35', '36', '37', '38', '39', '40', '41'],
  colors: ['Black', 'Cognac', 'Chocolate'],
  stockQuantity: 40,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'w-bt-002', sku: 'AUR-W-BT-002', title: 'Chelsea Ankle Boot', brand: 'AUREN', category: 'Boots', gender: 'Women', price: 295, rating: 4.7, reviewCount: 512, image: "https://img.rocket.new/generatedImages/rocket_gen_img_18eaf2a6d-1765254159501.png", description: 'Classic Chelsea boot in premium leather. Elastic side gussets, stacked heel.',
  tags: ['chelsea', 'ankle boot', 'classic', 'leather'],
  sizes: ['35', '36', '37', '38', '39', '40', '41'],
  colors: ['Black', 'Tan', 'Burgundy'],
  stockQuantity: 70,
  inStock: true
},
// ─── WOMEN'S BAGS ──────────────────────────────────────────────────────────
{
  id: 'w-bg-001',
  sku: 'AUR-W-BG-001',
  title: 'Structured Top-Handle Bag',
  brand: 'AUREN',
  category: 'Bags',
  gender: 'Women',
  price: 395,
  rating: 4.8,
  reviewCount: 287,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1bc531b09-1772156742380.png",
  description: 'Structured top-handle bag in smooth calf leather. Gold hardware, suede interior, detachable strap.',
  tags: ['top-handle', 'structured', 'leather', 'luxury'],
  sizes: ['One Size'],
  colors: ['Black', 'Camel', 'Ivory', 'Burgundy'],
  stockQuantity: 30,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'w-bg-002',
  sku: 'AUR-W-BG-002',
  title: 'Woven Raffia Tote',
  brand: 'AUREN',
  category: 'Bags',
  gender: 'Women',
  price: 175,
  rating: 4.5,
  reviewCount: 198,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1af089884-1772732598706.png",
  description: 'Handwoven raffia tote with leather handles and a zip closure. Lined interior.',
  tags: ['raffia', 'tote', 'summer', 'woven'],
  sizes: ['One Size'],
  colors: ['Natural', 'Black', 'Tan'],
  stockQuantity: 50,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'w-bg-003',
  sku: 'AUR-W-BG-003',
  title: 'Mini Crossbody Bag',
  brand: 'AUREN',
  category: 'Bags',
  gender: 'Women',
  price: 245,
  originalPrice: 295,
  rating: 4.7,
  reviewCount: 412,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_15a30923b-1770278019973.png",
  description: 'Compact crossbody bag in pebbled leather. Adjustable chain strap, magnetic closure.',
  tags: ['crossbody', 'mini', 'chain', 'evening'],
  sizes: ['One Size'],
  colors: ['Black', 'Nude', 'Dusty Rose', 'Cobalt'],
  stockQuantity: 45,
  inStock: true,
  badge: 'Sale'
},
{
  id: 'w-bg-004',
  sku: 'AUR-W-BG-004',
  title: 'Leather Bucket Bag',
  brand: 'AUREN',
  category: 'Bags',
  gender: 'Women',
  price: 315,
  rating: 4.6,
  reviewCount: 234,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_168f45413-1772068977032.png",
  description: 'Soft bucket bag in vegetable-tanned leather. Drawstring closure, detachable pouch.',
  tags: ['bucket bag', 'leather', 'casual', 'everyday'],
  sizes: ['One Size'],
  colors: ['Tan', 'Black', 'Chocolate'],
  stockQuantity: 38,
  inStock: true
},
// ─── WOMEN'S JEWELLERY ─────────────────────────────────────────────────────
{
  id: 'w-jw-001', sku: 'AUR-W-JW-001', title: 'Gold Vermeil Hoop Earrings', brand: 'AUREN', category: 'Jewellery', gender: 'Women', price: 85, rating: 4.8, reviewCount: 634, image: "https://img.rocket.new/generatedImages/rocket_gen_img_15e65c529-1767543673816.png", description: '18k gold vermeil hoop earrings. 30mm diameter, lightweight, hypoallergenic posts.',
  tags: ['hoops', 'gold', 'vermeil', 'everyday'],
  sizes: ['One Size'],
  colors: ['Gold'],
  stockQuantity: 120,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'w-jw-002', sku: 'AUR-W-JW-002', title: 'Delicate Chain Necklace', brand: 'AUREN', category: 'Jewellery', gender: 'Women', price: 65, rating: 4.7, reviewCount: 489, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1dcec68c7-1765225697950.png", description: 'Fine 18k gold-plated chain necklace. 45cm length with a 5cm extender.',
  tags: ['necklace', 'chain', 'gold', 'minimalist'],
  sizes: ['One Size'],
  colors: ['Gold', 'Silver'],
  stockQuantity: 150,
  inStock: true
},
{
  id: 'w-jw-003', sku: 'AUR-W-JW-003', title: 'Pearl Drop Earrings', brand: 'AUREN', category: 'Jewellery', gender: 'Women', price: 95, rating: 4.9, reviewCount: 312, image: "https://img.rocket.new/generatedImages/rocket_gen_img_120a93a92-1772215169833.png", description: 'Freshwater pearl drop earrings on a gold vermeil setting. 8mm pearls.',
  tags: ['pearl', 'drop earrings', 'elegant', 'classic'],
  sizes: ['One Size'],
  colors: ['White Pearl / Gold', 'White Pearl / Silver'],
  stockQuantity: 80,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'w-jw-004', sku: 'AUR-W-JW-004', title: 'Stacking Ring Set', brand: 'AUREN', category: 'Jewellery', gender: 'Women', price: 75, rating: 4.6, reviewCount: 267, image: "https://img.rocket.new/generatedImages/rocket_gen_img_14a133f5e-1782795508260.png", description: 'Set of 3 stacking rings in 18k gold vermeil. Thin band, twisted band, and beaded band.',
  tags: ['rings', 'stacking', 'gold', 'set'],
  sizes: ['5', '6', '7', '8'],
  colors: ['Gold', 'Silver', 'Rose Gold'],
  stockQuantity: 95,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'w-jw-005', sku: 'AUR-W-JW-005', title: 'Cuff Bracelet — Hammered Gold', brand: 'AUREN', category: 'Jewellery', gender: 'Women', price: 115, rating: 4.7, reviewCount: 198, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1f8b25979-1772514465406.png", description: 'Open cuff bracelet in hammered 18k gold-plated brass. Adjustable fit.',
  tags: ['cuff', 'bracelet', 'gold', 'statement'],
  sizes: ['One Size'],
  colors: ['Gold', 'Silver'],
  stockQuantity: 60,
  inStock: true
},
// ─── WOMEN'S SUNGLASSES ────────────────────────────────────────────────────
{
  id: 'w-sg-001',
  sku: 'AUR-W-SG-001',
  title: 'Oversized Square Sunglasses',
  brand: 'AUREN',
  category: 'Sunglasses',
  gender: 'Women',
  price: 145,
  rating: 4.7,
  reviewCount: 312,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_175313523-1772915199409.png",
  description: 'Oversized square frames in acetate. UV400 polarised lenses, spring hinges.',
  tags: ['oversized', 'square', 'polarised', 'summer'],
  sizes: ['One Size'],
  colors: ['Black', 'Tortoise', 'Clear'],
  stockQuantity: 65,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'w-sg-002',
  sku: 'AUR-W-SG-002',
  title: 'Cat-Eye Sunglasses',
  brand: 'AUREN',
  category: 'Sunglasses',
  gender: 'Women',
  price: 125,
  rating: 4.6,
  reviewCount: 245,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_15ed82b06-1764712498542.png",
  description: 'Classic cat-eye silhouette in lightweight acetate. UV400 lenses, gold-tone hardware.',
  tags: ['cat-eye', 'retro', 'acetate', 'classic'],
  sizes: ['One Size'],
  colors: ['Black', 'Tortoise', 'Ivory'],
  stockQuantity: 55,
  inStock: true,
  badge: 'New Arrival'
},
// ─── MEN'S SHIRTS ──────────────────────────────────────────────────────────
{
  id: 'm-sh-001', sku: 'AUR-M-SH-001', title: 'Oxford Button-Down Shirt', brand: 'AUREN', category: 'Shirts', gender: 'Men', price: 125, rating: 4.7, reviewCount: 687, image: "https://img.rocket.new/generatedImages/rocket_gen_img_11c4756d5-1772375675273.png", description: 'Classic Oxford cloth button-down shirt. Regular fit, chest pocket, barrel cuffs.',
  tags: ['oxford', 'button-down', 'classic', 'workwear'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['White', 'Light Blue', 'Pink', 'Sage'],
  stockQuantity: 120,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'm-sh-002', sku: 'AUR-M-SH-002', title: 'Linen Relaxed Shirt', brand: 'AUREN', category: 'Shirts', gender: 'Men', price: 115, rating: 4.6, reviewCount: 412, image: "https://img.rocket.new/generatedImages/rocket_gen_img_14e9da448-1766086472760.png", description: 'Relaxed-fit linen shirt. Spread collar, chest pocket, curved hem. Perfect for warm weather.',
  tags: ['linen', 'relaxed', 'summer', 'casual'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['White', 'Sand', 'Navy', 'Sage', 'Terracotta'],
  stockQuantity: 100,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'm-sh-003', sku: 'AUR-M-SH-003', title: 'Slim-Fit Dress Shirt', brand: 'AUREN', category: 'Shirts', gender: 'Men', price: 145, rating: 4.8, reviewCount: 523, image: "https://img.rocket.new/generatedImages/rocket_gen_img_175daa440-1773219588312.png", description: 'Slim-fit dress shirt in premium two-ply cotton. Spread collar, French cuffs.',
  tags: ['dress shirt', 'slim-fit', 'formal', 'premium'],
  sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  colors: ['White', 'Light Blue', 'Pale Pink'],
  stockQuantity: 85,
  inStock: true
},
{
  id: 'm-sh-004', sku: 'AUR-M-SH-004', title: 'Flannel Check Shirt', brand: 'AUREN', category: 'Shirts', gender: 'Men', price: 105, originalPrice: 135, rating: 4.5, reviewCount: 298, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1f16a4e96-1778254277546.png", description: 'Soft brushed flannel shirt in a classic check pattern. Regular fit, chest pockets.',
  tags: ['flannel', 'check', 'casual', 'autumn'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['Navy Check', 'Red Check', 'Green Check'],
  stockQuantity: 75,
  inStock: true,
  badge: 'Sale'
},
// ─── MEN'S T-SHIRTS ────────────────────────────────────────────────────────
{
  id: 'm-ts-001',
  sku: 'AUR-M-TS-001',
  title: 'Pima Cotton Essential Tee',
  brand: 'AUREN',
  category: 'T-Shirts',
  gender: 'Men',
  price: 55,
  rating: 4.8,
  reviewCount: 1243,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_192ba61f1-1777501657505.png",
  description: '100% Pima cotton crew-neck tee. Regular fit, pre-washed for softness. The perfect essential.',
  tags: ['pima', 'cotton', 'essential', 'basic'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['White', 'Black', 'Grey Marl', 'Navy', 'Olive'],
  stockQuantity: 250,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'm-ts-002',
  sku: 'AUR-M-TS-002',
  title: 'Heavyweight Boxy Tee',
  brand: 'AUREN',
  category: 'T-Shirts',
  gender: 'Men',
  price: 65,
  rating: 4.6,
  reviewCount: 534,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_188627b2b-1776876096579.png",
  description: '240gsm heavyweight cotton. Boxy fit, dropped shoulders, ribbed collar.',
  tags: ['heavyweight', 'boxy', 'oversized', 'streetwear'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['White', 'Black', 'Washed Olive', 'Washed Navy'],
  stockQuantity: 180,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'm-ts-003',
  sku: 'AUR-M-TS-003',
  title: 'Merino Wool V-Neck Tee',
  brand: 'AUREN',
  category: 'T-Shirts',
  gender: 'Men',
  price: 95,
  rating: 4.7,
  reviewCount: 287,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_13c7fea5e-1773122125487.png",
  description: 'Fine-gauge merino wool V-neck tee. Slim fit, temperature-regulating, odour-resistant.',
  tags: ['merino', 'v-neck', 'premium', 'travel'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['White', 'Black', 'Navy', 'Charcoal'],
  stockQuantity: 90,
  inStock: true
},
// ─── MEN'S POLO SHIRTS ─────────────────────────────────────────────────────
{
  id: 'm-po-001', sku: 'AUR-M-PO-001', title: 'Piqué Cotton Polo Shirt', brand: 'AUREN', category: 'Polo Shirts', gender: 'Men', price: 95, rating: 4.7, reviewCount: 512, image: "https://img.rocket.new/generatedImages/rocket_gen_img_157ad3ee2-1765742244652.png", description: 'Classic piqué cotton polo. Regular fit, ribbed collar and cuffs, three-button placket.',
  tags: ['polo', 'piqué', 'classic', 'smart-casual'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['White', 'Navy', 'Black', 'Sage', 'Burgundy'],
  stockQuantity: 130,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'm-po-002', sku: 'AUR-M-PO-002', title: 'Merino Polo Shirt', brand: 'AUREN', category: 'Polo Shirts', gender: 'Men', price: 145, rating: 4.8, reviewCount: 312, image: "https://img.rocket.new/generatedImages/rocket_gen_img_13f24b931-1772859183549.png", description: 'Fine-gauge merino wool polo. Slim fit, ribbed collar, two-button placket. Wrinkle-resistant.',
  tags: ['merino', 'polo', 'premium', 'smart'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Navy', 'Charcoal', 'Camel', 'Forest Green'],
  stockQuantity: 75,
  inStock: true,
  badge: 'New Arrival'
},
// ─── MEN'S JEANS ───────────────────────────────────────────────────────────
{
  id: 'm-jn-001',
  sku: 'AUR-M-JN-001',
  title: 'Slim Straight Selvedge Jeans',
  brand: 'AUREN',
  category: 'Jeans',
  gender: 'Men',
  price: 195,
  rating: 4.8,
  reviewCount: 634,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_187ee4b96-1764925789540.png",
  description: 'Slim straight jeans in Japanese selvedge denim. Five-pocket styling, raw hem.',
  tags: ['selvedge', 'slim straight', 'japanese denim', 'premium'],
  sizes: ['28', '29', '30', '31', '32', '33', '34', '36'],
  colors: ['Indigo', 'Black', 'Dark Wash'],
  stockQuantity: 90,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'm-jn-002',
  sku: 'AUR-M-JN-002',
  title: 'Relaxed Tapered Jeans',
  brand: 'AUREN',
  category: 'Jeans',
  gender: 'Men',
  price: 165,
  rating: 4.6,
  reviewCount: 412,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_155b0bd94-1772499325658.png",
  description: 'Relaxed through the thigh, tapered to the ankle. Soft stretch denim for all-day comfort.',
  tags: ['relaxed', 'tapered', 'stretch', 'casual'],
  sizes: ['28', '29', '30', '31', '32', '33', '34', '36'],
  colors: ['Mid Wash', 'Light Wash', 'Black'],
  stockQuantity: 110,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'm-jn-003',
  sku: 'AUR-M-JN-003',
  title: 'Straight Leg Jeans — Light Wash',
  brand: 'AUREN',
  category: 'Jeans',
  gender: 'Men',
  price: 145,
  originalPrice: 185,
  rating: 4.5,
  reviewCount: 298,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_197d9b141-1764852867587.png",
  description: 'Classic straight leg in a light wash denim. Regular rise, five-pocket styling.',
  tags: ['straight leg', 'light wash', 'classic', 'casual'],
  sizes: ['28', '29', '30', '31', '32', '33', '34', '36'],
  colors: ['Light Wash', 'Mid Wash'],
  stockQuantity: 85,
  inStock: true,
  badge: 'Sale'
},
// ─── MEN'S CHINOS ──────────────────────────────────────────────────────────
{
  id: 'm-ch-001', sku: 'AUR-M-CH-001', title: 'Slim Chino Trousers', brand: 'AUREN', category: 'Chinos', gender: 'Men', price: 135, rating: 4.7, reviewCount: 523, image: "https://img.rocket.new/generatedImages/rocket_gen_img_180f84e94-1772112160532.png", description: 'Slim-fit chino in stretch cotton twill. Flat front, side pockets, ankle length.',
  tags: ['chino', 'slim', 'smart-casual', 'versatile'],
  sizes: ['28', '29', '30', '31', '32', '33', '34', '36'],
  colors: ['Khaki', 'Navy', 'Olive', 'Charcoal', 'Stone'],
  stockQuantity: 115,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'm-ch-002', sku: 'AUR-M-CH-002', title: 'Relaxed Chino — Garment Dyed', brand: 'AUREN', category: 'Chinos', gender: 'Men', price: 145, rating: 4.6, reviewCount: 287, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1bc52618b-1772159087371.png", description: 'Garment-dyed chino in a relaxed fit. Soft cotton canvas, elasticated waistband.',
  tags: ['chino', 'relaxed', 'garment-dyed', 'casual'],
  sizes: ['28', '30', '32', '34', '36'],
  colors: ['Dusty Rose', 'Sage', 'Sand', 'Washed Navy'],
  stockQuantity: 70,
  inStock: true,
  badge: 'New Arrival'
},
// ─── MEN'S PANTS ───────────────────────────────────────────────────────────
{
  id: 'm-pt-001',
  sku: 'AUR-M-PT-001',
  title: 'Tailored Wool Trousers',
  brand: 'AUREN',
  category: 'Pants',
  gender: 'Men',
  price: 245,
  rating: 4.8,
  reviewCount: 312,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_17b051cc6-1772354892991.png",
  description: 'Tailored trousers in a premium Italian wool blend. Flat front, side pockets, pressed crease.',
  tags: ['tailored', 'wool', 'formal', 'premium'],
  sizes: ['28', '30', '32', '34', '36'],
  colors: ['Charcoal', 'Navy', 'Black', 'Camel'],
  stockQuantity: 55,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'm-pt-002',
  sku: 'AUR-M-PT-002',
  title: 'Cargo Trousers',
  brand: 'AUREN',
  category: 'Pants',
  gender: 'Men',
  price: 155,
  rating: 4.5,
  reviewCount: 398,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_149c53f09-1772074933263.png",
  description: 'Relaxed cargo trousers in cotton ripstop. Multiple pockets, elasticated ankle cuffs.',
  tags: ['cargo', 'utility', 'relaxed', 'streetwear'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['Olive', 'Black', 'Sand', 'Charcoal'],
  stockQuantity: 90,
  inStock: true,
  badge: 'New Arrival'
},
// ─── MEN'S SHORTS ──────────────────────────────────────────────────────────
{
  id: 'm-so-001', sku: 'AUR-M-SO-001', title: 'Linen Drawstring Shorts', brand: 'AUREN', category: 'Shorts', gender: 'Men', price: 85, rating: 4.6, reviewCount: 312, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1b74f103d-1772686419692.png", description: 'Relaxed linen shorts with a drawstring waist. Side pockets, mid-thigh length.',
  tags: ['linen', 'drawstring', 'summer', 'casual'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['Sand', 'White', 'Navy', 'Sage', 'Terracotta'],
  stockQuantity: 110,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'm-so-002', sku: 'AUR-M-SO-002', title: 'Tailored Chino Shorts', brand: 'AUREN', category: 'Shorts', gender: 'Men', price: 95, rating: 4.5, reviewCount: 245, image: "https://img.rocket.new/generatedImages/rocket_gen_img_10f822251-1773162755357.png", description: 'Smart chino shorts in stretch cotton. Flat front, side pockets, above-knee length.',
  tags: ['chino', 'tailored', 'smart-casual', 'summer'],
  sizes: ['28', '30', '32', '34', '36'],
  colors: ['Khaki', 'Navy', 'Stone', 'Olive'],
  stockQuantity: 85,
  inStock: true
},
// ─── MEN'S JACKETS ─────────────────────────────────────────────────────────
{
  id: 'm-jk-001',
  sku: 'AUR-M-JK-001',
  title: 'Harrington Jacket',
  brand: 'AUREN',
  category: 'Jackets',
  gender: 'Men',
  price: 245,
  rating: 4.7,
  reviewCount: 412,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_134e70ad8-1769856334264.png",
  description: 'Classic Harrington jacket in a cotton-blend. Ribbed collar, cuffs and hem, tartan lining.',
  tags: ['harrington', 'classic', 'casual', 'heritage'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['Olive', 'Navy', 'Black', 'Camel'],
  stockQuantity: 65,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'm-jk-002',
  sku: 'AUR-M-JK-002',
  title: 'Waxed Cotton Field Jacket',
  brand: 'AUREN',
  category: 'Jackets',
  gender: 'Men',
  price: 345,
  rating: 4.8,
  reviewCount: 287,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1b9b3ab7c-1779270701369.png",
  description: 'Waxed cotton field jacket with a corduroy collar. Multiple pockets, storm cuffs.',
  tags: ['waxed cotton', 'field jacket', 'heritage', 'utility'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['Olive', 'Dark Navy', 'Chocolate'],
  stockQuantity: 45,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'm-jk-003',
  sku: 'AUR-M-JK-003',
  title: 'Quilted Puffer Jacket',
  brand: 'AUREN',
  category: 'Jackets',
  gender: 'Men',
  price: 295,
  originalPrice: 365,
  rating: 4.6,
  reviewCount: 389,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1345dfd14-1774047263705.png",
  description: 'Lightweight quilted puffer with recycled down fill. Stand collar, zip pockets, packable.',
  tags: ['puffer', 'quilted', 'down', 'winter'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['Black', 'Navy', 'Olive', 'Charcoal'],
  stockQuantity: 70,
  inStock: true,
  badge: 'Sale'
},
// ─── MEN'S HOODIES ─────────────────────────────────────────────────────────
{
  id: 'm-hd-001', sku: 'AUR-M-HD-001', title: 'Heavyweight Zip-Up Hoodie', brand: 'AUREN', category: 'Hoodies', gender: 'Men', price: 145, rating: 4.7, reviewCount: 634, image: "https://img.rocket.new/generatedImages/rocket_gen_img_14f885a1d-1778255668517.png", description: '380gsm heavyweight cotton zip-up hoodie. Relaxed fit, kangaroo pocket, metal zip.',
  tags: ['zip-up', 'heavyweight', 'casual', 'streetwear'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['Black', 'Grey Marl', 'Navy', 'Olive'],
  stockQuantity: 120,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'm-hd-002', sku: 'AUR-M-HD-002', title: 'Pullover Fleece Hoodie', brand: 'AUREN', category: 'Hoodies', gender: 'Men', price: 125, rating: 4.6, reviewCount: 489, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1788c161e-1764649786630.png", description: 'Soft fleece pullover hoodie. Relaxed fit, kangaroo pocket, drawstring hood.',
  tags: ['fleece', 'pullover', 'casual', 'cosy'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['Grey Marl', 'Black', 'Navy', 'Forest Green'],
  stockQuantity: 140,
  inStock: true
},
// ─── MEN'S SWEATSHIRTS ─────────────────────────────────────────────────────
{
  id: 'm-sw-001',
  sku: 'AUR-M-SW-001',
  title: 'French Terry Crewneck Sweatshirt',
  brand: 'AUREN',
  category: 'Sweatshirts',
  gender: 'Men',
  price: 115,
  rating: 4.7,
  reviewCount: 712,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1ccf06f73-1780616817061.png",
  description: 'Classic crewneck sweatshirt in heavyweight French terry. Ribbed collar, cuffs and hem.',
  tags: ['crewneck', 'french terry', 'classic', 'casual'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['Grey Marl', 'Black', 'Navy', 'Oat', 'Burgundy'],
  stockQuantity: 160,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'm-sw-002',
  sku: 'AUR-M-SW-002',
  title: 'Vintage Wash Graphic Sweatshirt',
  brand: 'AUREN',
  category: 'Sweatshirts',
  gender: 'Men',
  price: 125,
  rating: 4.5,
  reviewCount: 398,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_13c1935f4-1779113904114.png",
  description: 'Vintage-washed crewneck with a subtle AUREN graphic. Boxy fit, dropped shoulders.',
  tags: ['graphic', 'vintage wash', 'boxy', 'streetwear'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['Washed Black', 'Washed Grey', 'Washed Navy'],
  stockQuantity: 95,
  inStock: true,
  badge: 'New Arrival'
},
// ─── MEN'S KNITWEAR ────────────────────────────────────────────────────────
{
  id: 'm-kn-001', sku: 'AUR-M-KN-001', title: 'Merino Crewneck Sweater', brand: 'AUREN', category: 'Knitwear', gender: 'Men', price: 185, rating: 4.8, reviewCount: 534, image: "https://img.rocket.new/generatedImages/rocket_gen_img_13c7fea5e-1773122125487.png", description: 'Fine-gauge merino wool crewneck. Regular fit, ribbed cuffs and hem. Machine washable.',
  tags: ['merino', 'crewneck', 'wool', 'essential'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['Navy', 'Charcoal', 'Camel', 'Forest Green', 'Burgundy'],
  stockQuantity: 85,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'm-kn-002', sku: 'AUR-M-KN-002', title: 'Chunky Knit Rollneck', brand: 'AUREN', category: 'Knitwear', gender: 'Men', price: 215, rating: 4.7, reviewCount: 287, image: "https://img.rocket.new/generatedImages/rocket_gen_img_11b634743-1773694779964.png", description: 'Oversized chunky-knit rollneck in a premium wool blend. Relaxed fit, ribbed throughout.',
  tags: ['chunky knit', 'rollneck', 'oversized', 'winter'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Oat', 'Charcoal', 'Camel', 'Black'],
  stockQuantity: 60,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'm-kn-003', sku: 'AUR-M-KN-003', title: 'Cashmere Crewneck Sweater', brand: 'AUREN', category: 'Knitwear', gender: 'Men', price: 295, originalPrice: 365, rating: 4.9, reviewCount: 312, image: "https://img.rocket.new/generatedImages/rocket_gen_img_101a8f6e4-1767171055972.png", description: 'Grade-A cashmere crewneck. Regular fit, ribbed trim. Exceptionally soft and warm.',
  tags: ['cashmere', 'crewneck', 'luxury', 'premium'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Navy', 'Charcoal', 'Camel', 'Black', 'Ivory'],
  stockQuantity: 45,
  inStock: true,
  badge: 'Sale'
},
// ─── MEN'S COATS ───────────────────────────────────────────────────────────
{
  id: 'm-ct-001',
  sku: 'AUR-M-CT-001',
  title: 'Wool Overcoat',
  brand: 'AUREN',
  category: 'Coats',
  gender: 'Men',
  price: 595,
  rating: 4.9,
  reviewCount: 287,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_16a1b93b5-1772278897887.png",
  description: 'Classic single-breasted overcoat in a premium Italian wool blend. Notch lapel, fully lined.',
  tags: ['overcoat', 'wool', 'classic', 'formal'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['Charcoal', 'Camel', 'Navy', 'Black'],
  stockQuantity: 35,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'm-ct-002',
  sku: 'AUR-M-CT-002',
  title: 'Double-Breasted Peacoat',
  brand: 'AUREN',
  category: 'Coats',
  gender: 'Men',
  price: 445,
  rating: 4.7,
  reviewCount: 198,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1098a1a20-1765082188022.png",
  description: 'Classic double-breasted peacoat in a wool-blend fabric. Peak lapels, anchor buttons.',
  tags: ['peacoat', 'double-breasted', 'heritage', 'winter'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['Navy', 'Black', 'Charcoal'],
  stockQuantity: 42,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'm-ct-003',
  sku: 'AUR-M-CT-003',
  title: 'Longline Trench Coat',
  brand: 'AUREN',
  category: 'Coats',
  gender: 'Men',
  price: 495,
  originalPrice: 595,
  rating: 4.8,
  reviewCount: 234,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1ddddab20-1781353332583.png",
  description: 'Classic double-breasted trench coat in water-resistant cotton gabardine. Storm flap, epaulettes.',
  tags: ['trench', 'classic', 'water-resistant', 'timeless'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['Camel', 'Black', 'Navy'],
  stockQuantity: 30,
  inStock: true,
  badge: 'Sale'
},
// ─── MEN'S SNEAKERS ────────────────────────────────────────────────────────
{
  id: 'm-sn-001', sku: 'AUR-M-SN-001', title: 'Low-Top Leather Sneaker', brand: 'AUREN', category: 'Sneakers', gender: 'Men', price: 225, rating: 4.8, reviewCount: 634, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1f6a589af-1772894744264.png", description: 'Clean low-top sneaker in smooth calf leather. Cupsole construction, leather lining.',
  tags: ['sneaker', 'leather', 'clean', 'everyday'],
  sizes: ['40', '41', '42', '43', '44', '45', '46'],
  colors: ['White', 'Black', 'Navy'],
  stockQuantity: 90,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'm-sn-002', sku: 'AUR-M-SN-002', title: 'Suede Retro Runner', brand: 'AUREN', category: 'Sneakers', gender: 'Men', price: 195, rating: 4.6, reviewCount: 412, image: "https://img.rocket.new/generatedImages/rocket_gen_img_171e984e3-1772218103822.png", description: 'Retro-inspired runner in premium suede. Chunky EVA midsole, contrast sole.',
  tags: ['retro', 'suede', 'runner', 'casual'],
  sizes: ['40', '41', '42', '43', '44', '45', '46'],
  colors: ['Camel', 'Grey', 'Navy', 'Black'],
  stockQuantity: 75,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'm-sn-003', sku: 'AUR-M-SN-003', title: 'High-Top Canvas Sneaker', brand: 'AUREN', category: 'Sneakers', gender: 'Men', price: 145, originalPrice: 185, rating: 4.5, reviewCount: 287, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1c9d5a537-1766904817384.png", description: 'Classic high-top in premium canvas. Vulcanised rubber sole, metal eyelets.',
  tags: ['high-top', 'canvas', 'classic', 'casual'],
  sizes: ['40', '41', '42', '43', '44', '45', '46'],
  colors: ['White', 'Black', 'Olive'],
  stockQuantity: 80,
  inStock: true,
  badge: 'Sale'
},
// ─── MEN'S BOOTS ───────────────────────────────────────────────────────────
{
  id: 'm-bt-001',
  sku: 'AUR-M-BT-001',
  title: 'Chelsea Boot — Leather',
  brand: 'AUREN',
  category: 'Boots',
  gender: 'Men',
  price: 345,
  rating: 4.8,
  reviewCount: 512,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_18eaf2a6d-1765254159501.png",
  description: 'Classic Chelsea boot in smooth calf leather. Elastic side gussets, stacked leather heel.',
  tags: ['chelsea', 'leather', 'classic', 'smart'],
  sizes: ['40', '41', '42', '43', '44', '45', '46'],
  colors: ['Black', 'Tan', 'Chocolate'],
  stockQuantity: 60,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'm-bt-002',
  sku: 'AUR-M-BT-002',
  title: 'Lace-Up Derby Boot',
  brand: 'AUREN',
  category: 'Boots',
  gender: 'Men',
  price: 295,
  rating: 4.7,
  reviewCount: 312,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1e4ddbd09-1772264614396.png",
  description: 'Rugged derby boot in full-grain leather. Commando sole, Goodyear welt construction.',
  tags: ['derby', 'lace-up', 'goodyear welt', 'heritage'],
  sizes: ['40', '41', '42', '43', '44', '45', '46'],
  colors: ['Dark Brown', 'Black', 'Cognac'],
  stockQuantity: 50,
  inStock: true,
  badge: 'New Arrival'
},
// ─── MEN'S WATCHES ─────────────────────────────────────────────────────────
{
  id: 'm-wt-001', sku: 'AUR-M-WT-001', title: 'Minimalist Field Watch', brand: 'AUREN', category: 'Watches', gender: 'Men', price: 395, rating: 4.8, reviewCount: 287, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1dd5235d3-1776430326504.png", description: 'Clean minimalist field watch with a Swiss quartz movement. 40mm case, sapphire crystal, leather strap.',
  tags: ['watch', 'minimalist', 'field watch', 'swiss'],
  sizes: ['One Size'],
  colors: ['Black Dial / Black Strap', 'White Dial / Tan Strap', 'Navy Dial / Navy Strap'],
  stockQuantity: 40,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'm-wt-002', sku: 'AUR-M-WT-002', title: 'Automatic Dress Watch', brand: 'AUREN', category: 'Watches', gender: 'Men', price: 695, rating: 4.9, reviewCount: 198, image: "https://img.rocket.new/generatedImages/rocket_gen_img_199de8660-1772969037397.png", description: 'Automatic movement dress watch. 38mm stainless steel case, exhibition caseback, alligator strap.',
  tags: ['watch', 'automatic', 'dress watch', 'luxury'],
  sizes: ['One Size'],
  colors: ['Silver / Black Strap', 'Gold / Brown Strap'],
  stockQuantity: 20,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'm-wt-003', sku: 'AUR-M-WT-003', title: 'Sport Chronograph Watch', brand: 'AUREN', category: 'Watches', gender: 'Men', price: 545, originalPrice: 645, rating: 4.7, reviewCount: 156, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1ee16da19-1773513527083.png", description: 'Chronograph sport watch with a 42mm case. 100m water resistance, rubber strap.',
  tags: ['watch', 'chronograph', 'sport', 'water-resistant'],
  sizes: ['One Size'],
  colors: ['Black / Black Strap', 'Silver / Blue Strap'],
  stockQuantity: 30,
  inStock: true,
  badge: 'Sale'
},
// ─── MEN'S BAGS ────────────────────────────────────────────────────────────
{
  id: 'm-bg-001',
  sku: 'AUR-M-BG-001',
  title: 'Leather Weekender Bag',
  brand: 'AUREN',
  category: 'Bags',
  gender: 'Men',
  price: 445,
  rating: 4.8,
  reviewCount: 198,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_188be4a27-1772275821918.png",
  description: 'Full-grain leather weekender bag. Zip closure, shoe compartment, detachable shoulder strap.',
  tags: ['weekender', 'leather', 'travel', 'premium'],
  sizes: ['One Size'],
  colors: ['Dark Brown', 'Black', 'Cognac'],
  stockQuantity: 25,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'm-bg-002',
  sku: 'AUR-M-BG-002',
  title: 'Canvas Tote Bag',
  brand: 'AUREN',
  category: 'Bags',
  gender: 'Men',
  price: 85,
  rating: 4.5,
  reviewCount: 312,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_178faf459-1779624342897.png",
  description: 'Heavy-duty canvas tote with leather handles and base. Internal zip pocket.',
  tags: ['tote', 'canvas', 'everyday', 'casual'],
  sizes: ['One Size'],
  colors: ['Natural', 'Black', 'Navy'],
  stockQuantity: 80,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'm-bg-003',
  sku: 'AUR-M-BG-003',
  title: 'Leather Backpack',
  brand: 'AUREN',
  category: 'Bags',
  gender: 'Men',
  price: 365,
  originalPrice: 445,
  rating: 4.7,
  reviewCount: 245,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1c3de575e-1764808252620.png",
  description: 'Structured leather backpack. Padded laptop sleeve, multiple pockets, top handle.',
  tags: ['backpack', 'leather', 'laptop', 'work'],
  sizes: ['One Size'],
  colors: ['Black', 'Dark Brown', 'Cognac'],
  stockQuantity: 35,
  inStock: true,
  badge: 'Sale'
},
// ─── MEN'S SUNGLASSES ──────────────────────────────────────────────────────
{
  id: 'm-sg-001', sku: 'AUR-M-SG-001', title: 'Aviator Sunglasses', brand: 'AUREN', category: 'Sunglasses', gender: 'Men', price: 155, rating: 4.7, reviewCount: 412, image: "https://img.rocket.new/generatedImages/rocket_gen_img_175313523-1772915199409.png", description: 'Classic aviator sunglasses with metal frames. UV400 polarised lenses, spring hinges.',
  tags: ['aviator', 'polarised', 'classic', 'summer'],
  sizes: ['One Size'],
  colors: ['Gold / Green', 'Silver / Grey', 'Gold / Brown'],
  stockQuantity: 70,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'm-sg-002', sku: 'AUR-M-SG-002', title: 'Square Frame Sunglasses', brand: 'AUREN', category: 'Sunglasses', gender: 'Men', price: 135, rating: 4.6, reviewCount: 287, image: "https://img.rocket.new/generatedImages/rocket_gen_img_15ed82b06-1764712498542.png", description: 'Bold square frames in premium acetate. UV400 lenses, keyhole bridge.',
  tags: ['square', 'acetate', 'bold', 'casual'],
  sizes: ['One Size'],
  colors: ['Black', 'Tortoise', 'Clear'],
  stockQuantity: 55,
  inStock: true,
  badge: 'New Arrival'
},
// ─── MEN'S ACCESSORIES ─────────────────────────────────────────────────────
{
  id: 'm-ac-001',
  sku: 'AUR-M-AC-001',
  title: 'Merino Wool Scarf',
  brand: 'AUREN',
  category: 'Accessories',
  gender: 'Men',
  price: 95,
  rating: 4.7,
  reviewCount: 312,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_154bab75a-1772195717497.png",
  description: 'Soft merino wool scarf. 180x30cm, fringed ends. Lightweight and warm.',
  tags: ['scarf', 'merino', 'wool', 'winter'],
  sizes: ['One Size'],
  colors: ['Camel', 'Navy', 'Charcoal', 'Burgundy', 'Black'],
  stockQuantity: 85,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'm-ac-002',
  sku: 'AUR-M-AC-002',
  title: 'Leather Belt — Tan',
  brand: 'AUREN',
  category: 'Accessories',
  gender: 'Men',
  price: 85,
  rating: 4.6,
  reviewCount: 245,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1500cef0a-1764712499201.png",
  description: 'Full-grain leather belt with a polished silver buckle. 35mm width.',
  tags: ['belt', 'leather', 'classic', 'formal'],
  sizes: ['28', '30', '32', '34', '36', '38', '40'],
  colors: ['Tan', 'Black', 'Dark Brown'],
  stockQuantity: 100,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'm-ac-003',
  sku: 'AUR-M-AC-003',
  title: 'Cashmere Beanie',
  brand: 'AUREN',
  category: 'Accessories',
  gender: 'Men',
  price: 75,
  rating: 4.8,
  reviewCount: 398,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_11718c782-1764820614407.png",
  description: 'Ribbed cashmere beanie. Slouchy fit, folded cuff. Incredibly soft.',
  tags: ['beanie', 'cashmere', 'winter', 'luxury'],
  sizes: ['One Size'],
  colors: ['Charcoal', 'Camel', 'Navy', 'Black', 'Ivory'],
  stockQuantity: 90,
  inStock: true
},
{
  id: 'm-ac-004',
  sku: 'AUR-M-AC-004',
  title: 'Silk Pocket Square',
  brand: 'AUREN',
  category: 'Accessories',
  gender: 'Men',
  price: 45,
  rating: 4.5,
  reviewCount: 156,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_122eadf33-1782962550514.png",
  description: '100% silk pocket square. Hand-rolled edges. Classic paisley and solid options.',
  tags: ['pocket square', 'silk', 'formal', 'classic'],
  sizes: ['One Size'],
  colors: ['Navy Paisley', 'Burgundy Paisley', 'White', 'Ivory'],
  stockQuantity: 120,
  inStock: true
},
{
  id: 'm-ac-005',
  sku: 'AUR-M-AC-005',
  title: 'Leather Card Holder',
  brand: 'AUREN',
  category: 'Accessories',
  gender: 'Men',
  price: 65,
  rating: 4.7,
  reviewCount: 289,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_19de3c656-1773134546526.png",
  description: 'Slim card holder in vegetable-tanned leather. 4 card slots, centre pocket.',
  tags: ['card holder', 'leather', 'slim', 'minimalist'],
  sizes: ['One Size'],
  colors: ['Black', 'Tan', 'Dark Brown'],
  stockQuantity: 110,
  inStock: true,
  badge: 'New Arrival'
},
// ─── ADDITIONAL WOMEN'S PRODUCTS ───────────────────────────────────────────
{
  id: 'w-dr-006', sku: 'AUR-W-DR-006', title: 'Broderie Anglaise Mini Dress', brand: 'AUREN', category: 'Dresses', gender: 'Women', price: 195, rating: 4.6, reviewCount: 178, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1a30ae6f5-1772090375833.png", description: 'Delicate broderie anglaise mini dress. Square neckline, puff sleeves, cotton lining.',
  tags: ['broderie', 'mini', 'summer', 'romantic'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['White', 'Ivory'],
  stockQuantity: 45,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'w-dr-007', sku: 'AUR-W-DR-007', title: 'Knit Bodycon Midi Dress', brand: 'AUREN', category: 'Dresses', gender: 'Women', price: 175, rating: 4.5, reviewCount: 234, image: "https://img.rocket.new/generatedImages/rocket_gen_img_14b3e7efe-1779865310889.png", description: 'Ribbed knit bodycon midi dress. Scoop neck, long sleeves, figure-skimming silhouette.',
  tags: ['knit', 'bodycon', 'midi', 'evening'],
  sizes: ['XS', 'S', 'M', 'L'],
  colors: ['Black', 'Chocolate', 'Dusty Rose'],
  stockQuantity: 50,
  inStock: true
},
{
  id: 'w-tp-005', sku: 'AUR-W-TP-005', title: 'Lace-Trim Slip Top', brand: 'AUREN', category: 'Tops', gender: 'Women', price: 85, rating: 4.6, reviewCount: 198, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1bd41b549-1772898227568.png", description: 'Delicate lace-trim slip top in a satin-finish fabric. Adjustable straps, relaxed fit.',
  tags: ['lace', 'slip', 'satin', 'elegant'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Ivory', 'Black', 'Blush'],
  stockQuantity: 65,
  inStock: true
},
{
  id: 'w-tp-006', sku: 'AUR-W-TP-006', title: 'Smocked Puff-Sleeve Top', brand: 'AUREN', category: 'Tops', gender: 'Women', price: 95, rating: 4.5, reviewCount: 156, image: "https://img.rocket.new/generatedImages/rocket_gen_img_15e771f40-1767489214231.png", description: 'Smocked bodice top with puff sleeves in a lightweight cotton voile. Square neckline.',
  tags: ['smocked', 'puff sleeve', 'cotton', 'romantic'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['White', 'Sage', 'Dusty Blue'],
  stockQuantity: 55,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'w-sh-003', sku: 'AUR-W-SH-003', title: 'Striped Cotton Shirt', brand: 'AUREN', category: 'Shirts', gender: 'Women', price: 105, rating: 4.5, reviewCount: 289, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1b9daddbb-1772087839116.png", description: 'Classic Breton-stripe cotton shirt. Relaxed fit, chest pocket, curved hem.',
  tags: ['stripe', 'breton', 'cotton', 'classic'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Navy Stripe', 'Red Stripe', 'Black Stripe'],
  stockQuantity: 80,
  inStock: true
},
{
  id: 'w-ts-003', sku: 'AUR-W-TS-003', title: 'Longline Fitted Tee', brand: 'AUREN', category: 'T-Shirts', gender: 'Women', price: 60, rating: 4.5, reviewCount: 312, image: "https://images.unsplash.com/photo-1666358057084-5f63d94d6958", description: 'Longline fitted tee in a soft cotton-modal blend. Crew neck, curved hem.',
  tags: ['longline', 'fitted', 'modal', 'essential'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['White', 'Black', 'Grey', 'Navy', 'Blush'],
  stockQuantity: 120,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'w-pt-003', sku: 'AUR-W-PT-003', title: 'Pleated Crepe Trousers', brand: 'AUREN', category: 'Pants', gender: 'Women', price: 175, rating: 4.6, reviewCount: 198, image: "https://img.rocket.new/generatedImages/rocket_gen_img_12be6c5d4-1772208510299.png", description: 'High-waisted pleated trousers in a fluid crepe fabric. Tapered leg, side pockets.',
  tags: ['pleated', 'crepe', 'tailored', 'workwear'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Black', 'Ivory', 'Camel', 'Sage'],
  stockQuantity: 60,
  inStock: true
},
{
  id: 'w-sk-004', sku: 'AUR-W-SK-004', title: 'Satin Bias-Cut Midi Skirt', brand: 'AUREN', category: 'Skirts', gender: 'Women', price: 155, rating: 4.7, reviewCount: 267, image: "https://img.rocket.new/generatedImages/rocket_gen_img_176a953f9-1772125906711.png", description: 'Bias-cut midi skirt in a luxurious satin fabric. Elasticated waist, fluid drape.',
  tags: ['satin', 'bias-cut', 'midi', 'elegant'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Champagne', 'Black', 'Dusty Rose', 'Cobalt'],
  stockQuantity: 50,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'w-bl-003', sku: 'AUR-W-BL-003', title: 'Cropped Tailored Blazer', brand: 'AUREN', category: 'Blazers', gender: 'Women', price: 265, rating: 4.7, reviewCount: 198, image: "https://img.rocket.new/generatedImages/rocket_gen_img_14ff65d78-1764698223168.png", description: 'Cropped single-breasted blazer in a stretch wool blend. Notch lapel, welt pockets.',
  tags: ['cropped', 'blazer', 'tailored', 'workwear'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Black', 'Ivory', 'Camel', 'Navy'],
  stockQuantity: 45,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'w-jk-003', sku: 'AUR-W-JK-003', title: 'Denim Trucker Jacket', brand: 'AUREN', category: 'Jackets', gender: 'Women', price: 175, rating: 4.6, reviewCount: 312, image: "https://img.rocket.new/generatedImages/rocket_gen_img_151cb9898-1772273307052.png", description: 'Classic denim trucker jacket in a relaxed fit. Button-front, chest pockets.',
  tags: ['denim', 'trucker', 'classic', 'casual'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Indigo', 'Light Wash', 'Black'],
  stockQuantity: 70,
  inStock: true
},
{
  id: 'w-hd-003', sku: 'AUR-W-HD-003', title: 'Cropped Zip-Up Hoodie', brand: 'AUREN', category: 'Hoodies', gender: 'Women', price: 115, rating: 4.5, reviewCount: 245, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1f6513076-1772614917287.png", description: 'Cropped zip-up hoodie in a soft cotton-blend fleece. Fitted hood, ribbed cuffs.',
  tags: ['cropped', 'zip-up', 'casual', 'athleisure'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['White', 'Black', 'Grey', 'Blush'],
  stockQuantity: 85,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'w-kn-004', sku: 'AUR-W-KN-004', title: 'Ribbed Knit Vest', brand: 'AUREN', category: 'Knitwear', gender: 'Women', price: 115, rating: 4.6, reviewCount: 198, image: "https://img.rocket.new/generatedImages/rocket_gen_img_16f9427d3-1775926723048.png", description: 'Ribbed knit vest in a merino-blend. V-neck, relaxed fit. Wear alone or layered.',
  tags: ['vest', 'ribbed', 'merino', 'layering'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Ivory', 'Black', 'Camel', 'Sage'],
  stockQuantity: 65,
  inStock: true
},
{
  id: 'w-sw-001', sku: 'AUR-W-SW-001', title: 'Leather Oxford Shoe', brand: 'AUREN', category: 'Shoes', gender: 'Women', price: 245, rating: 4.7, reviewCount: 198, image: "https://img.rocket.new/generatedImages/rocket_gen_img_12839cb5a-1766740915345.png", description: 'Classic Oxford in smooth calf leather. Lace-up front, stacked heel, leather sole.',
  tags: ['oxford', 'leather', 'classic', 'smart'],
  sizes: ['35', '36', '37', '38', '39', '40', '41'],
  colors: ['Black', 'Tan', 'Burgundy'],
  stockQuantity: 55,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'w-sa-003', sku: 'AUR-W-SA-003', title: 'Toe-Post Leather Sandal', brand: 'AUREN', category: 'Sandals', gender: 'Women', price: 125, rating: 4.5, reviewCount: 178, image: "https://img.rocket.new/generatedImages/rocket_gen_img_12a7892ae-1772156858081.png", description: 'Minimalist toe-post sandal in vegetable-tanned leather. Flat sole, leather footbed.',
  tags: ['toe-post', 'leather', 'flat', 'minimal'],
  sizes: ['35', '36', '37', '38', '39', '40', '41'],
  colors: ['Tan', 'Black', 'White'],
  stockQuantity: 65,
  inStock: true
},
{
  id: 'w-hl-003', sku: 'AUR-W-HL-003', title: 'Strappy Kitten Heel', brand: 'AUREN', category: 'Heels', gender: 'Women', price: 195, rating: 4.6, reviewCount: 156, image: "https://img.rocket.new/generatedImages/rocket_gen_img_1d980b2e5-1772902437418.png", description: 'Delicate strappy sandal with a 45mm kitten heel. Ankle strap, leather sole.',
  tags: ['kitten heel', 'strappy', 'elegant', 'evening'],
  sizes: ['35', '36', '37', '38', '39', '40', '41'],
  colors: ['Nude', 'Black', 'Gold'],
  stockQuantity: 45,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'w-bt-003', sku: 'AUR-W-BT-003', title: 'Suede Ankle Boot', brand: 'AUREN', category: 'Boots', gender: 'Women', price: 265, originalPrice: 325, rating: 4.7, reviewCount: 289, image: "https://images.unsplash.com/photo-1605733513549-de9b150bd70d", description: 'Ankle boot in premium suede. Block heel, inside zip, pointed toe.',
  tags: ['suede', 'ankle boot', 'block heel', 'autumn'],
  sizes: ['35', '36', '37', '38', '39', '40', '41'],
  colors: ['Camel', 'Black', 'Chocolate'],
  stockQuantity: 55,
  inStock: true,
  badge: 'Sale'
},
{
  id: 'w-bg-005', sku: 'AUR-W-BG-005', title: 'Quilted Chain Shoulder Bag', brand: 'AUREN', category: 'Bags', gender: 'Women', price: 285, rating: 4.8, reviewCount: 312, image: "https://img.rocket.new/generatedImages/rocket_gen_img_19908108d-1772068977249.png", description: 'Quilted lambskin shoulder bag with a gold chain strap. Flap closure, magnetic snap.',
  tags: ['quilted', 'chain', 'shoulder bag', 'evening'],
  sizes: ['One Size'],
  colors: ['Black', 'Ivory', 'Blush'],
  stockQuantity: 35,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'w-jw-006', sku: 'AUR-W-JW-006', title: 'Tennis Bracelet', brand: 'AUREN', category: 'Jewellery', gender: 'Women', price: 145, rating: 4.8, reviewCount: 198, image: "https://img.rocket.new/generatedImages/rocket_gen_img_182cea7cb-1778042946121.png", description: 'Cubic zirconia tennis bracelet in 18k gold-plated sterling silver. 18cm length.',
  tags: ['tennis bracelet', 'cubic zirconia', 'gold', 'elegant'],
  sizes: ['One Size'],
  colors: ['Gold', 'Silver', 'Rose Gold'],
  stockQuantity: 70,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'w-sg-003', sku: 'AUR-W-SG-003', title: 'Round Tinted Sunglasses', brand: 'AUREN', category: 'Sunglasses', gender: 'Women', price: 115, rating: 4.5, reviewCount: 198, image: "https://img.rocket.new/generatedImages/rocket_gen_img_15ed82b06-1764712498542.png", description: 'Round frames with tinted lenses in lightweight acetate. UV400 protection.',
  tags: ['round', 'tinted', 'retro', 'summer'],
  sizes: ['One Size'],
  colors: ['Black / Smoke', 'Tortoise / Brown', 'Clear / Pink'],
  stockQuantity: 60,
  inStock: true
},
// ─── ADDITIONAL MEN'S PRODUCTS ─────────────────────────────────────────────
{
  id: 'm-sh-005',
  sku: 'AUR-M-SH-005',
  title: 'Chambray Work Shirt',
  brand: 'AUREN',
  category: 'Shirts',
  gender: 'Men',
  price: 115,
  rating: 4.6,
  reviewCount: 312,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_14405c068-1772822792570.png",
  description: 'Soft chambray work shirt. Regular fit, chest pockets, button-down collar.',
  tags: ['chambray', 'work shirt', 'casual', 'denim'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['Light Blue', 'Indigo', 'Grey'],
  stockQuantity: 90,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'm-ts-004',
  sku: 'AUR-M-TS-004',
  title: 'Long-Sleeve Pocket Tee',
  brand: 'AUREN',
  category: 'T-Shirts',
  gender: 'Men',
  price: 65,
  rating: 4.6,
  reviewCount: 389,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1ef5f0d02-1775291689808.png",
  description: 'Long-sleeve tee in a soft cotton-modal blend. Chest pocket, crew neck, relaxed fit.',
  tags: ['long-sleeve', 'pocket tee', 'modal', 'casual'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['White', 'Black', 'Navy', 'Olive', 'Charcoal'],
  stockQuantity: 130,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'm-po-003',
  sku: 'AUR-M-PO-003',
  title: 'Striped Piqué Polo',
  brand: 'AUREN',
  category: 'Polo Shirts',
  gender: 'Men',
  price: 105,
  rating: 4.5,
  reviewCount: 198,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_13f52334b-1772686422409.png",
  description: 'Classic striped piqué polo. Regular fit, ribbed collar and cuffs.',
  tags: ['polo', 'striped', 'piqué', 'smart-casual'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['Navy Stripe', 'Red Stripe', 'Green Stripe'],
  stockQuantity: 85,
  inStock: true
},
{
  id: 'm-ch-003',
  sku: 'AUR-M-CH-003',
  title: 'Pleated Wide-Leg Chinos',
  brand: 'AUREN',
  category: 'Chinos',
  gender: 'Men',
  price: 165,
  rating: 4.6,
  reviewCount: 198,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_16a36f40f-1766550180185.png",
  description: 'Wide-leg chinos with a pleated front. High waist, relaxed through the leg.',
  tags: ['wide-leg', 'pleated', 'relaxed', 'fashion'],
  sizes: ['28', '30', '32', '34', '36'],
  colors: ['Khaki', 'Charcoal', 'Sand'],
  stockQuantity: 55,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'm-pt-003',
  sku: 'AUR-M-PT-003',
  title: 'Drawstring Linen Trousers',
  brand: 'AUREN',
  category: 'Pants',
  gender: 'Men',
  price: 135,
  rating: 4.6,
  reviewCount: 267,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1e561e3dc-1772354893981.png",
  description: 'Relaxed linen trousers with a drawstring waist. Side pockets, tapered leg.',
  tags: ['linen', 'drawstring', 'relaxed', 'summer'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['Sand', 'White', 'Navy', 'Sage'],
  stockQuantity: 80,
  inStock: true
},
{
  id: 'm-so-003',
  sku: 'AUR-M-SO-003',
  title: 'Swim Shorts',
  brand: 'AUREN',
  category: 'Shorts',
  gender: 'Men',
  price: 75,
  rating: 4.5,
  reviewCount: 312,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1859cd8d5-1767762212752.png",
  description: 'Quick-dry swim shorts in a recycled polyester fabric. Elastic waist, mesh lining.',
  tags: ['swim shorts', 'quick-dry', 'beach', 'summer'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['Navy', 'Olive', 'Black', 'Terracotta'],
  stockQuantity: 100,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'm-jk-004',
  sku: 'AUR-M-JK-004',
  title: 'Leather Bomber Jacket',
  brand: 'AUREN',
  category: 'Jackets',
  gender: 'Men',
  price: 545,
  rating: 4.8,
  reviewCount: 198,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1b1777ba4-1772829024925.png",
  description: 'Premium lambskin leather bomber jacket. Ribbed collar, cuffs and hem, zip pockets.',
  tags: ['bomber', 'leather', 'premium', 'classic'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Black', 'Cognac', 'Dark Brown'],
  stockQuantity: 25,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'm-hd-003',
  sku: 'AUR-M-HD-003',
  title: 'Tie-Dye Hoodie',
  brand: 'AUREN',
  category: 'Hoodies',
  gender: 'Men',
  price: 135,
  rating: 4.4,
  reviewCount: 156,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_107911ff1-1778765520697.png",
  description: 'Hand-dyed tie-dye hoodie in heavyweight cotton. Relaxed fit, kangaroo pocket.',
  tags: ['tie-dye', 'hoodie', 'casual', 'streetwear'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['Blue Tie-Dye', 'Earth Tie-Dye', 'Pastel Tie-Dye'],
  stockQuantity: 45,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'm-sw-003',
  sku: 'AUR-M-SW-003',
  title: 'Half-Zip Sweatshirt',
  brand: 'AUREN',
  category: 'Sweatshirts',
  gender: 'Men',
  price: 135,
  rating: 4.6,
  reviewCount: 289,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1ccf06f73-1780616817061.png",
  description: 'Half-zip sweatshirt in a soft cotton-blend fleece. Funnel neck, ribbed cuffs.',
  tags: ['half-zip', 'sweatshirt', 'smart-casual', 'layering'],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  colors: ['Navy', 'Charcoal', 'Oat', 'Forest Green'],
  stockQuantity: 75,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'm-kn-004',
  sku: 'AUR-M-KN-004',
  title: 'Shawl-Collar Cardigan',
  brand: 'AUREN',
  category: 'Knitwear',
  gender: 'Men',
  price: 225,
  rating: 4.7,
  reviewCount: 198,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_19ce66c4d-1772157859289.png",
  description: 'Shawl-collar cardigan in a premium wool blend. Button front, patch pockets.',
  tags: ['shawl collar', 'cardigan', 'wool', 'classic'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Oat', 'Charcoal', 'Navy', 'Camel'],
  stockQuantity: 50,
  inStock: true
},
{
  id: 'm-ct-004',
  sku: 'AUR-M-CT-004',
  title: 'Shearling-Lined Coat',
  brand: 'AUREN',
  category: 'Coats',
  gender: 'Men',
  price: 695,
  rating: 4.8,
  reviewCount: 145,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1211af26c-1772126922334.png",
  description: 'Suede coat with a genuine shearling lining and collar. Button front, side pockets.',
  tags: ['shearling', 'suede', 'luxury', 'winter'],
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  colors: ['Tan / Ivory', 'Dark Brown / Brown'],
  stockQuantity: 18,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'm-sn-004',
  sku: 'AUR-M-SN-004',
  title: 'Knit Sock Trainer',
  brand: 'AUREN',
  category: 'Sneakers',
  gender: 'Men',
  price: 175,
  rating: 4.5,
  reviewCount: 234,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_133a73bc4-1772614918066.png",
  description: 'Sock-fit knit trainer with a lightweight EVA sole. Breathable, slip-on design.',
  tags: ['sock trainer', 'knit', 'lightweight', 'casual'],
  sizes: ['40', '41', '42', '43', '44', '45', '46'],
  colors: ['Black', 'White', 'Grey'],
  stockQuantity: 65,
  inStock: true
},
{
  id: 'm-bt-003',
  sku: 'AUR-M-BT-003',
  title: 'Suede Desert Boot',
  brand: 'AUREN',
  category: 'Boots',
  gender: 'Men',
  price: 245,
  rating: 4.7,
  reviewCount: 389,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1e9c70439-1765088799335.png",
  description: 'Classic desert boot in premium suede. Crepe sole, two-eyelet lace-up.',
  tags: ['desert boot', 'suede', 'crepe sole', 'classic'],
  sizes: ['40', '41', '42', '43', '44', '45', '46'],
  colors: ['Sand', 'Chocolate', 'Black'],
  stockQuantity: 70,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'm-wt-004',
  sku: 'AUR-M-WT-004',
  title: 'Slim Leather Strap Watch',
  brand: 'AUREN',
  category: 'Watches',
  gender: 'Men',
  price: 295,
  rating: 4.6,
  reviewCount: 178,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_179aa091a-1772283941539.png",
  description: 'Ultra-slim quartz watch with a 36mm case. Slim leather strap, mineral crystal.',
  tags: ['watch', 'slim', 'quartz', 'everyday'],
  sizes: ['One Size'],
  colors: ['Black Dial / Black Strap', 'White Dial / Brown Strap'],
  stockQuantity: 50,
  inStock: true
},
{
  id: 'm-bg-004',
  sku: 'AUR-M-BG-004',
  title: 'Nylon Messenger Bag',
  brand: 'AUREN',
  category: 'Bags',
  gender: 'Men',
  price: 145,
  rating: 4.5,
  reviewCount: 198,
  image: "https://images.unsplash.com/photo-1679038138004-4162c92209e9",
  description: 'Lightweight nylon messenger bag with a padded laptop sleeve. Adjustable strap.',
  tags: ['messenger', 'nylon', 'laptop', 'everyday'],
  sizes: ['One Size'],
  colors: ['Black', 'Olive', 'Navy'],
  stockQuantity: 65,
  inStock: true,
  badge: 'New Arrival'
},
{
  id: 'm-sg-003',
  sku: 'AUR-M-SG-003',
  title: 'Wayfarer Sunglasses',
  brand: 'AUREN',
  category: 'Sunglasses',
  gender: 'Men',
  price: 125,
  rating: 4.6,
  reviewCount: 312,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_15ed82b06-1764712498542.png",
  description: 'Classic wayfarer silhouette in premium acetate. UV400 polarised lenses.',
  tags: ['wayfarer', 'polarised', 'classic', 'casual'],
  sizes: ['One Size'],
  colors: ['Black', 'Tortoise', 'Navy'],
  stockQuantity: 70,
  inStock: true,
  badge: 'Bestseller'
},
{
  id: 'm-ac-006',
  sku: 'AUR-M-AC-006',
  title: 'Wool Flat Cap',
  brand: 'AUREN',
  category: 'Accessories',
  gender: 'Men',
  price: 65,
  rating: 4.6,
  reviewCount: 198,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1845ced91-1766086473544.png",
  description: 'Classic flat cap in a herringbone wool blend. Lined interior, adjustable back strap.',
  tags: ['flat cap', 'wool', 'heritage', 'classic'],
  sizes: ['S/M', 'L/XL'],
  colors: ['Grey Herringbone', 'Navy', 'Camel'],
  stockQuantity: 75,
  inStock: true
},
{
  id: 'm-ac-007',
  sku: 'AUR-M-AC-007',
  title: 'Leather Gloves',
  brand: 'AUREN',
  category: 'Accessories',
  gender: 'Men',
  price: 95,
  rating: 4.7,
  reviewCount: 156,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1b6e01b58-1781706882806.png",
  description: 'Nappa leather gloves with a cashmere lining. Classic cut, touchscreen-compatible fingertips.',
  tags: ['gloves', 'leather', 'cashmere', 'winter'],
  sizes: ['S', 'M', 'L', 'XL'],
  colors: ['Black', 'Dark Brown', 'Tan'],
  stockQuantity: 60,
  inStock: true,
  badge: 'New Arrival'
}];