export interface Product {
  id: string;
  title: string;
  brand: string;
  category: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviewCount: number;
  image: string;
  description: string;
  tags: string[];
  inStock: boolean;
  badge?: 'New' | 'Sale' | 'Popular' | 'Limited';
}

export const CATEGORIES = [
'Electronics',
'Fashion',
'Furniture',
'Beauty',
'Shoes',
'Gaming',
'Kitchen',
'Fitness',
'Books',
'Home Decor'] as
const;

export const PRODUCTS: Product[] = [
// Electronics
{
  id: 'prod-001',
  title: 'AirPods Pro (3rd Gen)',
  brand: 'Apple',
  category: 'Electronics',
  price: 249,
  rating: 4.8,
  reviewCount: 4821,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1099f262d-1773908592995.png",
  description: 'Active Noise Cancellation, Transparency mode, Adaptive Audio. Up to 30 hours total listening time.',
  tags: ['wireless', 'noise-cancelling', 'apple'],
  inStock: true,
  badge: 'Popular'
},
{
  id: 'prod-002',
  title: 'Sony WH-1000XM5 Headphones',
  brand: 'Sony',
  category: 'Electronics',
  price: 349,
  originalPrice: 399,
  rating: 4.7,
  reviewCount: 3204,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1b15f3582-1782806478633.png",
  description: 'Industry-leading noise cancellation with two processors and eight microphones.',
  tags: ['wireless', 'noise-cancelling', 'premium'],
  inStock: true,
  badge: 'Sale'
},
{
  id: 'prod-003',
  title: 'iPad Air 11-inch M2',
  brand: 'Apple',
  category: 'Electronics',
  price: 599,
  rating: 4.9,
  reviewCount: 2103,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1d6b05ab1-1765300022618.png",
  description: 'Supercharged by M2 chip. 11-inch Liquid Retina display. All-day battery life.',
  tags: ['tablet', 'apple', 'm2'],
  inStock: true,
  badge: 'New'
},
{
  id: 'prod-004',
  title: 'Samsung 4K OLED 55" TV',
  brand: 'Samsung',
  category: 'Electronics',
  price: 1299,
  originalPrice: 1599,
  rating: 4.6,
  reviewCount: 987,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_16837278f-1782880617150.png",
  description: 'OLED display with Quantum HDR OLED+, Neural Quantum Processor 4K.',
  tags: ['tv', 'oled', '4k'],
  inStock: true,
  badge: 'Sale'
},
{
  id: 'prod-005',
  title: 'Kindle Paperwhite Signature',
  brand: 'Amazon',
  category: 'Electronics',
  price: 189,
  rating: 4.7,
  reviewCount: 8432,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_192d1fee0-1782880617635.png",
  description: '6.8" display, wireless charging, 32 GB, auto-adjusting front light.',
  tags: ['ereader', 'kindle', 'reading'],
  inStock: true
},
{
  id: 'prod-006',
  title: 'DJI Mini 4 Pro Drone',
  brand: 'DJI',
  category: 'Electronics',
  price: 759,
  rating: 4.8,
  reviewCount: 1204,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_101108b60-1773709450025.png",
  description: '4K/60fps video, omnidirectional obstacle sensing, 34-min flight time.',
  tags: ['drone', 'camera', 'aerial'],
  inStock: true,
  badge: 'Popular'
},
// Fashion
{
  id: 'prod-007',
  title: 'Linen Blazer — Oat White',
  brand: 'COS',
  category: 'Fashion',
  price: 185,
  rating: 4.5,
  reviewCount: 342,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1567905b1-1767587100933.png",
  description: 'Relaxed-fit linen blazer with a notch lapel. Welt pockets. Fully lined.',
  tags: ['blazer', 'linen', 'minimalist'],
  inStock: true,
  badge: 'New'
},
{
  id: 'prod-008',
  title: 'Merino Wool Crewneck',
  brand: 'Everlane',
  category: 'Fashion',
  price: 110,
  originalPrice: 140,
  rating: 4.6,
  reviewCount: 891,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_13c7fea5e-1773122125487.png",
  description: '100% Grade-A Mongolian merino wool. Ribbed cuffs and hem. Machine washable.',
  tags: ['sweater', 'merino', 'sustainable'],
  inStock: true,
  badge: 'Sale'
},
{
  id: 'prod-009',
  title: 'Wide-Leg Trousers — Charcoal',
  brand: 'Arket',
  category: 'Fashion',
  price: 95,
  rating: 4.4,
  reviewCount: 213,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_17b051cc6-1772354892991.png",
  description: 'High-waisted wide-leg trousers in a wool-blend fabric. Side pockets.',
  tags: ['trousers', 'wool', 'wide-leg'],
  inStock: true
},
{
  id: 'prod-010',
  title: 'Silk Slip Dress — Champagne',
  brand: 'Reformation',
  category: 'Fashion',
  price: 218,
  rating: 4.7,
  reviewCount: 567,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_15311d694-1772225337403.png",
  description: 'Recycled silk blend. Adjustable spaghetti straps. Midi length.',
  tags: ['dress', 'silk', 'sustainable'],
  inStock: true,
  badge: 'Popular'
},
{
  id: 'prod-011',
  title: 'Oversized Denim Jacket',
  brand: "Levi\'s",
  category: 'Fashion',
  price: 128,
  originalPrice: 158,
  rating: 4.5,
  reviewCount: 1043,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_14f63be68-1766808046304.png",
  description: 'Classic trucker jacket in a relaxed, oversized fit. Button-front closure.',
  tags: ['denim', 'jacket', 'classic'],
  inStock: true,
  badge: 'Sale'
},
{
  id: 'prod-012',
  title: 'Cashmere Turtleneck',
  brand: 'Uniqlo',
  category: 'Fashion',
  price: 79,
  rating: 4.8,
  reviewCount: 2341,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_18f178568-1768305954021.png",
  description: 'Premium Grade-A cashmere. Slim fit turtleneck. Available in 12 colors.',
  tags: ['cashmere', 'turtleneck', 'luxury'],
  inStock: true
},
// Furniture
{
  id: 'prod-013',
  title: 'Wabi Sabi Sofa — Sage',
  brand: 'IKEA',
  category: 'Furniture',
  price: 1299,
  rating: 4.4,
  reviewCount: 432,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1555eab76-1772803665246.png",
  description: 'Low-profile 3-seater sofa with removable covers in sage green boucle.',
  tags: ['sofa', 'boucle', 'minimalist'],
  inStock: true,
  badge: 'Popular'
},
{
  id: 'prod-014',
  title: 'Solid Oak Dining Table',
  brand: 'Made.com',
  category: 'Furniture',
  price: 849,
  originalPrice: 1049,
  rating: 4.6,
  reviewCount: 287,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1945031fd-1772259002338.png",
  description: 'Solid FSC-certified oak. Seats 6. Tapered leg detail. 180x90cm.',
  tags: ['dining', 'oak', 'sustainable'],
  inStock: true,
  badge: 'Sale'
},
{
  id: 'prod-015',
  title: 'Rattan Accent Chair',
  brand: 'West Elm',
  category: 'Furniture',
  price: 449,
  rating: 4.3,
  reviewCount: 198,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1c0d859d4-1772803670936.png",
  description: 'Handwoven rattan frame with removable linen cushion. Indoor/outdoor.',
  tags: ['chair', 'rattan', 'boho'],
  inStock: true
},
{
  id: 'prod-016',
  title: 'Marble Coffee Table',
  brand: 'CB2',
  category: 'Furniture',
  price: 699,
  rating: 4.5,
  reviewCount: 341,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1921999f1-1772601616313.png",
  description: 'Genuine Carrara marble top on a brushed brass steel frame. 100x60cm.',
  tags: ['coffee table', 'marble', 'luxury'],
  inStock: true,
  badge: 'New'
},
{
  id: 'prod-017',
  title: 'Platform Bed Frame — Walnut',
  brand: 'Floyd',
  category: 'Furniture',
  price: 895,
  rating: 4.7,
  reviewCount: 521,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_10dfcefad-1772601618690.png",
  description: 'Solid American walnut platform bed. No box spring needed. Queen size.',
  tags: ['bed', 'walnut', 'platform'],
  inStock: true
},
{
  id: 'prod-018',
  title: 'Modular Bookshelf System',
  brand: 'String Furniture',
  category: 'Furniture',
  price: 580,
  originalPrice: 680,
  rating: 4.8,
  reviewCount: 673,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_196af8626-1782880616547.png",
  description: 'Expandable wall-mounted shelving. Powder-coated steel. 6 color options.',
  tags: ['bookshelf', 'modular', 'storage'],
  inStock: true,
  badge: 'Sale'
},
// Beauty
{
  id: 'prod-019',
  title: 'Vitamin C Brightening Serum',
  brand: 'Paula\'s Choice',
  category: 'Beauty',
  price: 42,
  rating: 4.8,
  reviewCount: 6741,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1e16e1c19-1776056299969.png",
  description: '15% Vitamin C + E + Ferulic Acid. Brightens, firms, and evens skin tone.',
  tags: ['serum', 'vitamin c', 'brightening'],
  inStock: true,
  badge: 'Popular'
},
{
  id: 'prod-020',
  title: 'Dyson Airwrap Complete',
  brand: 'Dyson',
  category: 'Beauty',
  price: 599,
  rating: 4.6,
  reviewCount: 3214,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1da73aff7-1775079781291.png",
  description: 'Multi-styler and dryer. Coanda airflow to style and dry simultaneously.',
  tags: ['hair', 'styling', 'dyson'],
  inStock: true,
  badge: 'Popular'
},
{
  id: 'prod-021',
  title: 'Retinol Eye Cream',
  brand: 'Skinceuticals',
  category: 'Beauty',
  price: 98,
  rating: 4.5,
  reviewCount: 1823,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1516d5f43-1779477062079.png",
  description: '0.5% pure retinol. Reduces fine lines and dark circles. For all skin types.',
  tags: ['retinol', 'eye cream', 'anti-aging'],
  inStock: true
},
{
  id: 'prod-022',
  title: 'Gua Sha Facial Tool — Rose Quartz',
  brand: 'Mount Lai',
  category: 'Beauty',
  price: 34,
  originalPrice: 45,
  rating: 4.7,
  reviewCount: 4201,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1e85e2a56-1772072566031.png",
  description: 'Authentic rose quartz gua sha. Reduces puffiness, defines jawline.',
  tags: ['gua sha', 'rose quartz', 'facial'],
  inStock: true,
  badge: 'Sale'
},
{
  id: 'prod-023',
  title: 'SPF 50 Sunscreen Serum',
  brand: 'Supergoop',
  category: 'Beauty',
  price: 38,
  rating: 4.9,
  reviewCount: 9821,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1c009f521-1782880617533.png",
  description: 'Unseen Sunscreen. Invisible, weightless. No white cast. Oil-free.',
  tags: ['sunscreen', 'spf50', 'lightweight'],
  inStock: true,
  badge: 'Popular'
},
{
  id: 'prod-024',
  title: 'Lip Oil — Glazed Peach',
  brand: 'Dior',
  category: 'Beauty',
  price: 42,
  rating: 4.8,
  reviewCount: 2341,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1a8abd84a-1772444694876.png",
  description: 'Addict Lip Glow Oil. Plumping, hydrating, with a glossy finish.',
  tags: ['lip', 'gloss', 'dior'],
  inStock: true,
  badge: 'New'
},
// Shoes
{
  id: 'prod-025',
  title: 'New Balance 574 Core',
  brand: 'New Balance',
  category: 'Shoes',
  price: 89,
  rating: 4.7,
  reviewCount: 5432,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_15ffdc8cf-1767518572014.png",
  description: 'Classic 574 silhouette. Suede and mesh upper. ENCAP midsole cushioning.',
  tags: ['sneakers', 'running', 'casual'],
  inStock: true,
  badge: 'Popular'
},
{
  id: 'prod-026',
  title: 'Adidas Samba OG',
  brand: 'Adidas',
  category: 'Shoes',
  price: 100,
  rating: 4.8,
  reviewCount: 7821,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_17714d755-1777814844830.png",
  description: 'The iconic Samba. Leather upper, gum outsole, T-toe overlay.',
  tags: ['sneakers', 'samba', 'icon'],
  inStock: true,
  badge: 'Popular'
},
{
  id: 'prod-027',
  title: 'Chelsea Boots — Cognac',
  brand: 'Thursday Boot Co.',
  category: 'Shoes',
  price: 199,
  rating: 4.6,
  reviewCount: 2104,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_161fafdfb-1772156012782.png",
  description: 'Full-grain leather. Goodyear welt construction. Vibram outsole.',
  tags: ['boots', 'leather', 'chelsea'],
  inStock: true
},
{
  id: 'prod-028',
  title: 'Birkenstock Arizona Oiled',
  brand: 'Birkenstock',
  category: 'Shoes',
  price: 140,
  originalPrice: 165,
  rating: 4.7,
  reviewCount: 3891,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1069d3200-1772264617072.png",
  description: 'Oiled nubuck leather. Anatomical cork-latex footbed. Two strap buckles.',
  tags: ['sandals', 'birkenstock', 'comfort'],
  inStock: true,
  badge: 'Sale'
},
{
  id: 'prod-029',
  title: 'Nike Air Max 90',
  brand: 'Nike',
  category: 'Shoes',
  price: 130,
  rating: 4.6,
  reviewCount: 9234,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1659155fb-1780572956509.png",
  description: 'Iconic Max Air cushioning. Mesh and leather upper. Rubber waffle outsole.',
  tags: ['sneakers', 'air max', 'nike'],
  inStock: true
},
{
  id: 'prod-030',
  title: 'Loafers — Cream Leather',
  brand: 'Toteme',
  category: 'Shoes',
  price: 420,
  rating: 4.5,
  reviewCount: 431,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1d3fee52b-1772902430285.png",
  description: 'Square-toe leather loafers with a chunky block heel. Leather lining.',
  tags: ['loafers', 'leather', 'luxury'],
  inStock: true,
  badge: 'New'
},
// Gaming
{
  id: 'prod-031',
  title: 'PlayStation 5 Slim',
  brand: 'Sony',
  category: 'Gaming',
  price: 449,
  rating: 4.9,
  reviewCount: 12043,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_16f5921f9-1775963538541.png",
  description: 'Next-gen gaming with the PS5 Slim. 1TB SSD, 4K gaming, DualSense controller.',
  tags: ['console', 'playstation', 'next-gen'],
  inStock: true,
  badge: 'Popular'
},
{
  id: 'prod-032',
  title: 'Xbox Series X',
  brand: 'Microsoft',
  category: 'Gaming',
  price: 499,
  rating: 4.8,
  reviewCount: 8932,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1de255eec-1782880617154.png",
  description: 'World\'s most powerful console. 12 teraflops, 4K gaming at 120fps.',
  tags: ['console', 'xbox', 'next-gen'],
  inStock: true
},
{
  id: 'prod-033',
  title: 'Razer BlackWidow V4 Pro',
  brand: 'Razer',
  category: 'Gaming',
  price: 229,
  originalPrice: 279,
  rating: 4.7,
  reviewCount: 2341,
  image: "https://images.unsplash.com/photo-1649340511624-6125e0dee23a",
  description: 'Wireless mechanical keyboard. Razer Yellow switches. Chroma RGB.',
  tags: ['keyboard', 'mechanical', 'wireless'],
  inStock: true,
  badge: 'Sale'
},
{
  id: 'prod-034',
  title: 'Nintendo Switch OLED',
  brand: 'Nintendo',
  category: 'Gaming',
  price: 349,
  rating: 4.8,
  reviewCount: 15032,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1d5155915-1782880617405.png",
  description: '7" OLED screen, enhanced audio, 64GB storage. Play at home or on the go.',
  tags: ['console', 'nintendo', 'portable'],
  inStock: true,
  badge: 'Popular'
},
{
  id: 'prod-035',
  title: 'SteelSeries Arctis Nova Pro',
  brand: 'SteelSeries',
  category: 'Gaming',
  price: 249,
  rating: 4.6,
  reviewCount: 1823,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_11f528131-1766540637283.png",
  description: 'Premium wireless gaming headset. ANC, 40-hour battery, hi-fi audio.',
  tags: ['headset', 'wireless', 'gaming'],
  inStock: true
},
{
  id: 'prod-036',
  title: 'Logitech G Pro X Superlight 2',
  brand: 'Logitech',
  category: 'Gaming',
  price: 159,
  rating: 4.9,
  reviewCount: 4201,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1aa897165-1782178935931.png",
  description: 'Ultra-lightweight wireless gaming mouse. HERO 2 sensor, 95g.',
  tags: ['mouse', 'wireless', 'esports'],
  inStock: true,
  badge: 'Popular'
},
// Kitchen
{
  id: 'prod-037',
  title: 'Le Creuset Dutch Oven 5.5qt',
  brand: 'Le Creuset',
  category: 'Kitchen',
  price: 389,
  rating: 4.9,
  reviewCount: 7823,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_105240832-1782880617854.png",
  description: 'Enameled cast iron. Even heat distribution. Oven safe to 500°F. Cerise red.',
  tags: ['dutch oven', 'cast iron', 'cookware'],
  inStock: true,
  badge: 'Popular'
},
{
  id: 'prod-038',
  title: 'Vitamix E310 Explorian Blender',
  brand: 'Vitamix',
  category: 'Kitchen',
  price: 349,
  originalPrice: 449,
  rating: 4.8,
  reviewCount: 5234,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1fe226658-1775079782642.png",
  description: '10 variable speeds. 48oz container. 5-year full warranty. 2.2 peak HP motor.',
  tags: ['blender', 'vitamix', 'smoothies'],
  inStock: true,
  badge: 'Sale'
},
{
  id: 'prod-039',
  title: 'Breville Barista Express',
  brand: 'Breville',
  category: 'Kitchen',
  price: 699,
  rating: 4.7,
  reviewCount: 4102,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1f9139099-1777320418173.png",
  description: 'Built-in conical burr grinder. Dose-control grinding. Steam milk texturing.',
  tags: ['espresso', 'coffee', 'grinder'],
  inStock: true,
  badge: 'Popular'
},
{
  id: 'prod-040',
  title: 'Global 8-Piece Knife Set',
  brand: 'Global',
  category: 'Kitchen',
  price: 479,
  rating: 4.8,
  reviewCount: 1923,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_164ddd1f1-1782880618121.png",
  description: 'Cromova 18 stainless steel. Lightweight, perfectly balanced. Lifetime warranty.',
  tags: ['knives', 'japanese', 'professional'],
  inStock: true
},
{
  id: 'prod-041',
  title: 'Staub Cast Iron Skillet 12"',
  brand: 'Staub',
  category: 'Kitchen',
  price: 179,
  rating: 4.8,
  reviewCount: 3421,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_11069ef70-1777051678178.png",
  description: 'Enameled cast iron skillet with self-basting spikes. Matte black interior.',
  tags: ['skillet', 'cast iron', 'staub'],
  inStock: true
},
{
  id: 'prod-042',
  title: 'Instant Pot Duo 7-in-1',
  brand: 'Instant Pot',
  category: 'Kitchen',
  price: 99,
  originalPrice: 129,
  rating: 4.7,
  reviewCount: 21043,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1cad92680-1777996952168.png",
  description: 'Pressure cooker, slow cooker, rice cooker, steamer, sauté, yogurt maker, warmer.',
  tags: ['instant pot', 'pressure cooker', 'multi-cooker'],
  inStock: true,
  badge: 'Sale'
},
// Fitness
{
  id: 'prod-043',
  title: 'Lululemon Align Leggings 28"',
  brand: 'Lululemon',
  category: 'Fitness',
  price: 128,
  rating: 4.8,
  reviewCount: 14023,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_14aed2016-1773518947306.png",
  description: 'Nulu fabric. Buttery-soft, weightless feel. 4-way stretch. 28" inseam.',
  tags: ['leggings', 'yoga', 'lululemon'],
  inStock: true,
  badge: 'Popular'
},
{
  id: 'prod-044',
  title: 'Peloton Bike+ Gen 2',
  brand: 'Peloton',
  category: 'Fitness',
  price: 2495,
  rating: 4.6,
  reviewCount: 3421,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_19e25c6a7-1782880617691.png",
  description: '24" rotating HD touchscreen, auto-resistance, 10-point multitouch.',
  tags: ['cycling', 'peloton', 'cardio'],
  inStock: true,
  badge: 'Popular'
},
{
  id: 'prod-045',
  title: 'Adjustable Dumbbell Set 5-52.5lb',
  brand: 'Bowflex',
  category: 'Fitness',
  price: 299,
  originalPrice: 399,
  rating: 4.7,
  reviewCount: 8234,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_100c6fd64-1774013026249.png",
  description: 'SelectTech 552. 15 weight settings. Replaces 15 sets of weights.',
  tags: ['dumbbells', 'adjustable', 'strength'],
  inStock: true,
  badge: 'Sale'
},
{
  id: 'prod-046',
  title: 'WHOOP 4.0 Health Tracker',
  brand: 'WHOOP',
  category: 'Fitness',
  price: 239,
  rating: 4.5,
  reviewCount: 4123,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1effc0671-1782880616103.png",
  description: 'Continuous health monitoring. HRV, strain, recovery, sleep tracking.',
  tags: ['wearable', 'health', 'tracker'],
  inStock: true,
  badge: 'New'
},
{
  id: 'prod-047',
  title: 'Manduka PRO Yoga Mat',
  brand: 'Manduka',
  category: 'Fitness',
  price: 120,
  rating: 4.8,
  reviewCount: 6234,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_166b126df-1782425595510.png",
  description: '6mm thick. Lifetime guarantee. Closed-cell surface. 71" x 26".',
  tags: ['yoga mat', 'manduka', 'premium'],
  inStock: true
},
{
  id: 'prod-048',
  title: 'TRX Home Suspension Trainer',
  brand: 'TRX',
  category: 'Fitness',
  price: 189,
  rating: 4.6,
  reviewCount: 3421,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_17f1928a3-1782880620442.png",
  description: 'Professional-grade suspension trainer. Works anywhere. 300+ exercises.',
  tags: ['suspension', 'bodyweight', 'portable'],
  inStock: true
},
// Books
{
  id: 'prod-049',
  title: 'Atomic Habits — James Clear',
  brand: 'Avery Publishing',
  category: 'Books',
  price: 18,
  rating: 4.9,
  reviewCount: 89234,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_195c7f0da-1773906358113.png",
  description: 'The proven framework for improving every day. #1 New York Times bestseller.',
  tags: ['self-help', 'habits', 'bestseller'],
  inStock: true,
  badge: 'Popular'
},
{
  id: 'prod-050',
  title: 'The Design of Everyday Things',
  brand: 'Basic Books',
  category: 'Books',
  price: 22,
  rating: 4.7,
  reviewCount: 12043,
  image: "https://images.unsplash.com/photo-1667039487341-041db260dd87",
  description: 'Don Norman\'s classic on user-centered design. Essential reading for designers.',
  tags: ['design', 'ux', 'classic'],
  inStock: true
},
{
  id: 'prod-051',
  title: 'The Psychology of Money',
  brand: 'Harriman House',
  category: 'Books',
  price: 19,
  rating: 4.8,
  reviewCount: 34021,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1c8d50543-1776526845181.png",
  description: 'Morgan Housel on the strange ways people think about money. Financial wisdom.',
  tags: ['finance', 'psychology', 'money'],
  inStock: true,
  badge: 'Popular'
},
{
  id: 'prod-052',
  title: 'Dune — Frank Herbert',
  brand: 'Ace Books',
  category: 'Books',
  price: 16,
  rating: 4.8,
  reviewCount: 41023,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_121defed5-1772728891921.png",
  description: 'The greatest science fiction novel ever written. Set in a distant future.',
  tags: ['sci-fi', 'classic', 'epic'],
  inStock: true
},
{
  id: 'prod-053',
  title: 'Deep Work — Cal Newport',
  brand: 'Grand Central',
  category: 'Books',
  price: 17,
  rating: 4.7,
  reviewCount: 23041,
  image: "https://images.unsplash.com/photo-1623095211952-500344b1d42b",
  description: 'Rules for focused success in a distracted world. Essential productivity reading.',
  tags: ['productivity', 'focus', 'work'],
  inStock: true
},
{
  id: 'prod-054',
  title: 'Shoe Dog — Phil Knight',
  brand: 'Scribner',
  category: 'Books',
  price: 18,
  rating: 4.8,
  reviewCount: 28034,
  image: "https://images.unsplash.com/photo-1586755443491-1a22ce579e2f",
  description: 'A memoir by the creator of Nike. An extraordinary story of entrepreneurship.',
  tags: ['memoir', 'business', 'nike'],
  inStock: true
},
// Home Decor
{
  id: 'prod-055',
  title: 'Arco Floor Lamp — Brass',
  brand: 'Flos',
  category: 'Home Decor',
  price: 2890,
  rating: 4.9,
  reviewCount: 432,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_177798e8d-1780488019518.png",
  description: 'Iconic arc floor lamp by Achille Castiglioni. Marble base, brushed brass.',
  tags: ['lamp', 'iconic', 'designer'],
  inStock: true,
  badge: 'Popular'
},
{
  id: 'prod-056',
  title: 'Hay Dot Rug — Terracotta',
  brand: 'HAY',
  category: 'Home Decor',
  price: 349,
  originalPrice: 420,
  rating: 4.6,
  reviewCount: 287,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1e069921f-1772882301357.png",
  description: 'Tufted wool rug with a graphic dot pattern. 200x300cm. Hand-crafted.',
  tags: ['rug', 'wool', 'graphic'],
  inStock: true,
  badge: 'Sale'
},
{
  id: 'prod-057',
  title: 'Abstract Canvas Print Set',
  brand: 'Society6',
  category: 'Home Decor',
  price: 189,
  rating: 4.5,
  reviewCount: 1204,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1cb57456c-1780749468760.png",
  description: 'Set of 3 abstract prints. Gallery-wrapped canvas. 18x24" each.',
  tags: ['art', 'canvas', 'abstract'],
  inStock: true
},
{
  id: 'prod-058',
  title: 'Muuto Unfold Pendant Lamp',
  brand: 'Muuto',
  category: 'Home Decor',
  price: 320,
  rating: 4.7,
  reviewCount: 521,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_1a764d196-1779456295078.png",
  description: 'Spun aluminum pendant. E27 socket. Matte finish. Available in 8 colors.',
  tags: ['lamp', 'pendant', 'scandinavian'],
  inStock: true,
  badge: 'New'
},
{
  id: 'prod-059',
  title: 'Concrete Planter Set — Terrazzo',
  brand: 'Zara Home',
  category: 'Home Decor',
  price: 89,
  rating: 4.6,
  reviewCount: 832,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_148901100-1772803666783.png",
  description: 'Set of 3 terrazzo concrete planters. Drainage hole. Sizes S/M/L.',
  tags: ['planter', 'terrazzo', 'plants'],
  inStock: true
},
{
  id: 'prod-060',
  title: 'Linen Throw Blanket — Oat',
  brand: 'Hawkins New York',
  category: 'Home Decor',
  price: 128,
  rating: 4.8,
  reviewCount: 1923,
  image: "https://img.rocket.new/generatedImages/rocket_gen_img_11a72f0f3-1775604048158.png",
  description: '100% European linen. Stonewashed finish. 50x70". Machine washable.',
  tags: ['blanket', 'linen', 'cozy'],
  inStock: true
}];


export const BRANDS = [...new Set(PRODUCTS.map((p) => p.brand))].sort();